// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: test

#include "ui.h"

lv_obj_t * uic_DirectionPointer;
lv_obj_t * uic_DirectionSelectButtonLabel0;
lv_obj_t * uic_DirectionSelectButton0;
lv_obj_t * uic_DirectionSelectButtonLabel1;
lv_obj_t * uic_DirectionSelectButton1;
lv_obj_t * uic_DirectionSelectButtonLabel2;
lv_obj_t * uic_DirectionSelectButton2;
lv_obj_t * uic_DirectionSelect0;
lv_obj_t * uic_DirectionSelectButtonLabel4;
lv_obj_t * uic_DirectionSelectButton4;
lv_obj_t * uic_DirectionSelectButtonLabel3;
lv_obj_t * uic_DirectionSelectButton3;
lv_obj_t * uic_DirectionSelect1;
lv_obj_t * uic_Direction1;
lv_obj_t * uic_FreePanel;
lv_obj_t * uic_Label8;
lv_obj_t * uic_IdleButton;
lv_obj_t * uic_Label7;
lv_obj_t * uic_RunButton;
lv_obj_t * uic_Run;
lv_obj_t * uic_InterPositonCheckbox;
lv_obj_t * uic_MacaoShootCheckbox;
lv_obj_t * uic_Label4;
lv_obj_t * uic_BackButton0;
lv_obj_t * uic_DropDown0;
lv_obj_t * uic_ActionSelectAppScreen;
lv_obj_t * ui_ActionSelectAppScreen = NULL;
lv_obj_t * ui_DropDown0 = NULL;
lv_obj_t * ui_BackButton0 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_MacaoShootCheckbox = NULL;
lv_obj_t * ui_InterPositonCheckbox = NULL;
lv_obj_t * ui_Run = NULL;
lv_obj_t * ui_RunButton = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_IdleButton = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_FreePanel = NULL;
lv_obj_t * ui_Direction1 = NULL;
lv_obj_t * ui_DirectionSelect1 = NULL;
lv_obj_t * ui_DirectionSelectButton3 = NULL;
lv_obj_t * ui_DirectionSelectButtonLabel3 = NULL;
lv_obj_t * ui_DirectionSelectButton4 = NULL;
lv_obj_t * ui_DirectionSelectButtonLabel4 = NULL;
lv_obj_t * ui_DirectionSelect0 = NULL;
lv_obj_t * ui_DirectionSelectButton2 = NULL;
lv_obj_t * ui_DirectionSelectButtonLabel2 = NULL;
lv_obj_t * ui_DirectionSelectButton1 = NULL;
lv_obj_t * ui_DirectionSelectButtonLabel1 = NULL;
lv_obj_t * ui_DirectionSelectButton0 = NULL;
lv_obj_t * ui_DirectionSelectButtonLabel0 = NULL;
lv_obj_t * ui_DirectionPointer = NULL;
// event funtions
void ui_event_DropDown0(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ui_action_select_app_dropdown_func(e);
        ui_app_clear_settings_func(e);
    }
}

void ui_event_BackButton0(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_HomeScreen, LV_SCR_LOAD_ANIM_FADE_ON, 10, 0, &ui_HomeScreen_screen_init);
        ui_app_clear_settings_func(e);
    }
}

void ui_event_RunButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_IdleButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_RunButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_IdleButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_RunButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_IdleButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_DirectionSelectButton3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_DirectionSelectButton4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_DirectionSelectButton3, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_DirectionSelectButton4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_DirectionSelectButton3, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_DirectionSelectButton4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_DirectionSelectButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_DirectionSelectButton0, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_DirectionSelectButton2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_DirectionSelectButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_DirectionSelectButton2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_DirectionSelectButton1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_DirectionSelectButton0(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_DirectionSelectButton1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_DirectionSelectButton0, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

// build funtions

void ui_ActionSelectAppScreen_screen_init(void)
{
    ui_ActionSelectAppScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ActionSelectAppScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DropDown0 = lv_dropdown_create(ui_ActionSelectAppScreen);
    lv_dropdown_set_dir(ui_DropDown0, LV_DIR_TOP);
    lv_dropdown_set_options(ui_DropDown0, "Attacker\nDefender\nRadicon");
    lv_obj_set_width(ui_DropDown0, 248);
    lv_obj_set_height(ui_DropDown0, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_x(ui_DropDown0, 3);
    lv_obj_set_y(ui_DropDown0, 3);
    lv_obj_add_flag(ui_DropDown0, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_BackButton0 = lv_btn_create(ui_ActionSelectAppScreen);
    lv_obj_set_width(ui_BackButton0, 60);
    lv_obj_set_height(ui_BackButton0, 35);
    lv_obj_set_x(ui_BackButton0, 257);
    lv_obj_set_y(ui_BackButton0, 3);
    lv_obj_add_flag(ui_BackButton0, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BackButton0, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BackButton0, lv_color_hex(0xFF4F4F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BackButton0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_BackButton0);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "BACK");

    ui_MacaoShootCheckbox = lv_checkbox_create(ui_ActionSelectAppScreen);
    lv_checkbox_set_text(ui_MacaoShootCheckbox, "MacaoShoot");
    lv_obj_set_width(ui_MacaoShootCheckbox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MacaoShootCheckbox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MacaoShootCheckbox, 3);
    lv_obj_set_y(ui_MacaoShootCheckbox, 180);
    lv_obj_add_state(ui_MacaoShootCheckbox, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_MacaoShootCheckbox, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_InterPositonCheckbox = lv_checkbox_create(ui_ActionSelectAppScreen);
    lv_checkbox_set_text(ui_InterPositonCheckbox, "InterPositon");
    lv_obj_set_width(ui_InterPositonCheckbox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_InterPositonCheckbox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_InterPositonCheckbox, 3);
    lv_obj_set_y(ui_InterPositonCheckbox, 210);
    lv_obj_add_state(ui_InterPositonCheckbox, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_InterPositonCheckbox, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Run = lv_obj_create(ui_ActionSelectAppScreen);
    lv_obj_set_width(ui_Run, 186);
    lv_obj_set_height(ui_Run, 126);
    lv_obj_set_x(ui_Run, 0);
    lv_obj_set_y(ui_Run, 47);
    lv_obj_clear_flag(ui_Run, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Run, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Run, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Run, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Run, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RunButton = lv_btn_create(ui_Run);
    lv_obj_set_width(ui_RunButton, 180);
    lv_obj_set_height(ui_RunButton, 120);
    lv_obj_set_align(ui_RunButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RunButton, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_RunButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_RunButton, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RunButton, lv_color_hex(0x2DA041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RunButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_RunButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_RunButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_RunButton, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_RunButton, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_RunButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_RunButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RunButton, lv_color_hex(0x414141), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_opa(ui_RunButton, 255, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_color(ui_RunButton, lv_color_hex(0x2DA041), LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_bg_opa(ui_RunButton, 255, LV_PART_MAIN | LV_STATE_USER_2);

    ui_Label7 = lv_label_create(ui_RunButton);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "RUN");

    ui_IdleButton = lv_btn_create(ui_Run);
    lv_obj_set_width(ui_IdleButton, 180);
    lv_obj_set_height(ui_IdleButton, 120);
    lv_obj_set_align(ui_IdleButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IdleButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_IdleButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_IdleButton, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_IdleButton, lv_color_hex(0x414141), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IdleButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_IdleButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_IdleButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_IdleButton, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_IdleButton, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_IdleButton, lv_color_hex(0x414141), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_opa(ui_IdleButton, 255, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_color(ui_IdleButton, lv_color_hex(0x2DA041), LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_bg_opa(ui_IdleButton, 255, LV_PART_MAIN | LV_STATE_USER_2);

    ui_Label8 = lv_label_create(ui_IdleButton);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "IDLE");

    ui_FreePanel = lv_obj_create(ui_ActionSelectAppScreen);
    lv_obj_set_width(ui_FreePanel, 170);
    lv_obj_set_height(ui_FreePanel, 50);
    lv_obj_set_x(ui_FreePanel, 140);
    lv_obj_set_y(ui_FreePanel, 180);
    lv_obj_clear_flag(ui_FreePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Direction1 = lv_obj_create(ui_ActionSelectAppScreen);
    lv_obj_remove_style_all(ui_Direction1);
    lv_obj_set_width(ui_Direction1, 124);
    lv_obj_set_height(ui_Direction1, 124);
    lv_obj_set_x(ui_Direction1, 190);
    lv_obj_set_y(ui_Direction1, 48);
    lv_obj_clear_flag(ui_Direction1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DirectionSelect1 = lv_obj_create(ui_Direction1);
    lv_obj_set_width(ui_DirectionSelect1, 116);
    lv_obj_set_height(ui_DirectionSelect1, 116);
    lv_obj_set_align(ui_DirectionSelect1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DirectionSelect1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_DirectionSelect1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_DirectionSelect1, 58, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DirectionSelect1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DirectionSelect1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_DirectionSelect1, lv_color_hex(0xD5D2D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_DirectionSelect1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_DirectionSelect1, 7, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DirectionSelectButton3 = lv_btn_create(ui_DirectionSelect1);
    lv_obj_set_width(ui_DirectionSelectButton3, 74);
    lv_obj_set_height(ui_DirectionSelectButton3, 74);
    lv_obj_set_align(ui_DirectionSelectButton3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DirectionSelectButton3, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DirectionSelectButton3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DirectionSelectButton3, lv_color_hex(0xE7DF29), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DirectionSelectButton3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_DirectionSelectButton3, 0, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_color(ui_DirectionSelectButton3, lv_color_hex(0xD3D904), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_opa(ui_DirectionSelectButton3, 255, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_radius(ui_DirectionSelectButton3, 0, LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_bg_color(ui_DirectionSelectButton3, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_bg_opa(ui_DirectionSelectButton3, 255, LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_radius(ui_DirectionSelectButton3, 0, LV_PART_MAIN | LV_STATE_USER_3);
    lv_obj_set_style_bg_color(ui_DirectionSelectButton3, lv_color_hex(0x545454), LV_PART_MAIN | LV_STATE_USER_3);
    lv_obj_set_style_bg_opa(ui_DirectionSelectButton3, 255, LV_PART_MAIN | LV_STATE_USER_3);

    ui_DirectionSelectButtonLabel3 = lv_label_create(ui_DirectionSelectButton3);
    lv_obj_set_width(ui_DirectionSelectButtonLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DirectionSelectButtonLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DirectionSelectButtonLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DirectionSelectButtonLabel3, "YELLOW\nGOAL");

    ui_DirectionSelectButton4 = lv_btn_create(ui_DirectionSelect1);
    lv_obj_set_width(ui_DirectionSelectButton4, 74);
    lv_obj_set_height(ui_DirectionSelectButton4, 74);
    lv_obj_set_align(ui_DirectionSelectButton4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DirectionSelectButton4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DirectionSelectButton4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_DirectionSelectButton4, 0, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_color(ui_DirectionSelectButton4, lv_color_hex(0xD3D904), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_opa(ui_DirectionSelectButton4, 255, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_radius(ui_DirectionSelectButton4, 0, LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_bg_color(ui_DirectionSelectButton4, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_bg_opa(ui_DirectionSelectButton4, 255, LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_radius(ui_DirectionSelectButton4, 0, LV_PART_MAIN | LV_STATE_USER_3);
    lv_obj_set_style_bg_color(ui_DirectionSelectButton4, lv_color_hex(0x545454), LV_PART_MAIN | LV_STATE_USER_3);
    lv_obj_set_style_bg_opa(ui_DirectionSelectButton4, 255, LV_PART_MAIN | LV_STATE_USER_3);

    ui_DirectionSelectButtonLabel4 = lv_label_create(ui_DirectionSelectButton4);
    lv_obj_set_width(ui_DirectionSelectButtonLabel4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DirectionSelectButtonLabel4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DirectionSelectButtonLabel4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DirectionSelectButtonLabel4, "BLUE\nGOAL");

    ui_DirectionSelect0 = lv_obj_create(ui_Direction1);
    lv_obj_set_width(ui_DirectionSelect0, 116);
    lv_obj_set_height(ui_DirectionSelect0, 116);
    lv_obj_set_align(ui_DirectionSelect0, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_DirectionSelect0, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_DirectionSelect0, 58, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DirectionSelect0, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DirectionSelect0, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_DirectionSelect0, lv_color_hex(0xD5D2D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_DirectionSelect0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_DirectionSelect0, 7, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DirectionSelectButton2 = lv_btn_create(ui_DirectionSelect0);
    lv_obj_set_width(ui_DirectionSelectButton2, 74);
    lv_obj_set_height(ui_DirectionSelectButton2, 74);
    lv_obj_set_align(ui_DirectionSelectButton2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DirectionSelectButton2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DirectionSelectButton2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DirectionSelectButton2, lv_color_hex(0xD5D2D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DirectionSelectButton2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_DirectionSelectButton2, 0, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_color(ui_DirectionSelectButton2, lv_color_hex(0xD3D904), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_opa(ui_DirectionSelectButton2, 255, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_radius(ui_DirectionSelectButton2, 0, LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_bg_color(ui_DirectionSelectButton2, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_bg_opa(ui_DirectionSelectButton2, 255, LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_radius(ui_DirectionSelectButton2, 0, LV_PART_MAIN | LV_STATE_USER_3);
    lv_obj_set_style_bg_color(ui_DirectionSelectButton2, lv_color_hex(0x545454), LV_PART_MAIN | LV_STATE_USER_3);
    lv_obj_set_style_bg_opa(ui_DirectionSelectButton2, 255, LV_PART_MAIN | LV_STATE_USER_3);

    ui_DirectionSelectButtonLabel2 = lv_label_create(ui_DirectionSelectButton2);
    lv_obj_set_width(ui_DirectionSelectButtonLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DirectionSelectButtonLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DirectionSelectButtonLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DirectionSelectButtonLabel2, "GYRO");

    ui_DirectionSelectButton1 = lv_btn_create(ui_DirectionSelect0);
    lv_obj_set_width(ui_DirectionSelectButton1, 74);
    lv_obj_set_height(ui_DirectionSelectButton1, 74);
    lv_obj_set_align(ui_DirectionSelectButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DirectionSelectButton1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DirectionSelectButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DirectionSelectButton1, lv_color_hex(0xE7DF29), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DirectionSelectButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_DirectionSelectButton1, 0, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_color(ui_DirectionSelectButton1, lv_color_hex(0xD3D904), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_opa(ui_DirectionSelectButton1, 255, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_radius(ui_DirectionSelectButton1, 0, LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_bg_color(ui_DirectionSelectButton1, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_bg_opa(ui_DirectionSelectButton1, 255, LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_radius(ui_DirectionSelectButton1, 0, LV_PART_MAIN | LV_STATE_USER_3);
    lv_obj_set_style_bg_color(ui_DirectionSelectButton1, lv_color_hex(0x545454), LV_PART_MAIN | LV_STATE_USER_3);
    lv_obj_set_style_bg_opa(ui_DirectionSelectButton1, 255, LV_PART_MAIN | LV_STATE_USER_3);

    ui_DirectionSelectButtonLabel1 = lv_label_create(ui_DirectionSelectButton1);
    lv_obj_set_width(ui_DirectionSelectButtonLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DirectionSelectButtonLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DirectionSelectButtonLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DirectionSelectButtonLabel1, "YELLOW\nGOAL");

    ui_DirectionSelectButton0 = lv_btn_create(ui_DirectionSelect0);
    lv_obj_set_width(ui_DirectionSelectButton0, 74);
    lv_obj_set_height(ui_DirectionSelectButton0, 74);
    lv_obj_set_align(ui_DirectionSelectButton0, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DirectionSelectButton0, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DirectionSelectButton0, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_DirectionSelectButton0, 0, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_color(ui_DirectionSelectButton0, lv_color_hex(0xD3D904), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_opa(ui_DirectionSelectButton0, 255, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_radius(ui_DirectionSelectButton0, 0, LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_bg_color(ui_DirectionSelectButton0, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_bg_opa(ui_DirectionSelectButton0, 255, LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_radius(ui_DirectionSelectButton0, 0, LV_PART_MAIN | LV_STATE_USER_3);
    lv_obj_set_style_bg_color(ui_DirectionSelectButton0, lv_color_hex(0x545454), LV_PART_MAIN | LV_STATE_USER_3);
    lv_obj_set_style_bg_opa(ui_DirectionSelectButton0, 255, LV_PART_MAIN | LV_STATE_USER_3);

    ui_DirectionSelectButtonLabel0 = lv_label_create(ui_DirectionSelectButton0);
    lv_obj_set_width(ui_DirectionSelectButtonLabel0, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DirectionSelectButtonLabel0, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DirectionSelectButtonLabel0, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DirectionSelectButtonLabel0, "BLUE\nGOAL");

    ui_DirectionPointer = lv_obj_create(ui_Direction1);
    lv_obj_set_width(ui_DirectionPointer, 16);
    lv_obj_set_height(ui_DirectionPointer, 16);
    lv_obj_set_x(ui_DirectionPointer, 0);
    lv_obj_set_y(ui_DirectionPointer, -54);
    lv_obj_set_align(ui_DirectionPointer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_DirectionPointer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_DirectionPointer, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DirectionPointer, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DirectionPointer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_DirectionPointer, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_DirectionPointer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_DirectionPointer, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_DropDown0, ui_event_DropDown0, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BackButton0, ui_event_BackButton0, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RunButton, ui_event_RunButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_IdleButton, ui_event_IdleButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DirectionSelectButton3, ui_event_DirectionSelectButton3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DirectionSelectButton4, ui_event_DirectionSelectButton4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DirectionSelectButton2, ui_event_DirectionSelectButton2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DirectionSelectButton1, ui_event_DirectionSelectButton1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DirectionSelectButton0, ui_event_DirectionSelectButton0, LV_EVENT_ALL, NULL);
    uic_ActionSelectAppScreen = ui_ActionSelectAppScreen;
    uic_DropDown0 = ui_DropDown0;
    uic_BackButton0 = ui_BackButton0;
    uic_Label4 = ui_Label4;
    uic_MacaoShootCheckbox = ui_MacaoShootCheckbox;
    uic_InterPositonCheckbox = ui_InterPositonCheckbox;
    uic_Run = ui_Run;
    uic_RunButton = ui_RunButton;
    uic_Label7 = ui_Label7;
    uic_IdleButton = ui_IdleButton;
    uic_Label8 = ui_Label8;
    uic_FreePanel = ui_FreePanel;
    uic_Direction1 = ui_Direction1;
    uic_DirectionSelect1 = ui_DirectionSelect1;
    uic_DirectionSelectButton3 = ui_DirectionSelectButton3;
    uic_DirectionSelectButtonLabel3 = ui_DirectionSelectButtonLabel3;
    uic_DirectionSelectButton4 = ui_DirectionSelectButton4;
    uic_DirectionSelectButtonLabel4 = ui_DirectionSelectButtonLabel4;
    uic_DirectionSelect0 = ui_DirectionSelect0;
    uic_DirectionSelectButton2 = ui_DirectionSelectButton2;
    uic_DirectionSelectButtonLabel2 = ui_DirectionSelectButtonLabel2;
    uic_DirectionSelectButton1 = ui_DirectionSelectButton1;
    uic_DirectionSelectButtonLabel1 = ui_DirectionSelectButtonLabel1;
    uic_DirectionSelectButton0 = ui_DirectionSelectButton0;
    uic_DirectionSelectButtonLabel0 = ui_DirectionSelectButtonLabel0;
    uic_DirectionPointer = ui_DirectionPointer;

}

void ui_ActionSelectAppScreen_screen_destroy(void)
{
    if(ui_ActionSelectAppScreen) lv_obj_del(ui_ActionSelectAppScreen);

    // NULL screen variables
    uic_ActionSelectAppScreen = NULL;
    ui_ActionSelectAppScreen = NULL;
    uic_DropDown0 = NULL;
    ui_DropDown0 = NULL;
    uic_BackButton0 = NULL;
    ui_BackButton0 = NULL;
    uic_Label4 = NULL;
    ui_Label4 = NULL;
    uic_MacaoShootCheckbox = NULL;
    ui_MacaoShootCheckbox = NULL;
    uic_InterPositonCheckbox = NULL;
    ui_InterPositonCheckbox = NULL;
    uic_Run = NULL;
    ui_Run = NULL;
    uic_RunButton = NULL;
    ui_RunButton = NULL;
    uic_Label7 = NULL;
    ui_Label7 = NULL;
    uic_IdleButton = NULL;
    ui_IdleButton = NULL;
    uic_Label8 = NULL;
    ui_Label8 = NULL;
    uic_FreePanel = NULL;
    ui_FreePanel = NULL;
    uic_Direction1 = NULL;
    ui_Direction1 = NULL;
    uic_DirectionSelect1 = NULL;
    ui_DirectionSelect1 = NULL;
    uic_DirectionSelectButton3 = NULL;
    ui_DirectionSelectButton3 = NULL;
    uic_DirectionSelectButtonLabel3 = NULL;
    ui_DirectionSelectButtonLabel3 = NULL;
    uic_DirectionSelectButton4 = NULL;
    ui_DirectionSelectButton4 = NULL;
    uic_DirectionSelectButtonLabel4 = NULL;
    ui_DirectionSelectButtonLabel4 = NULL;
    uic_DirectionSelect0 = NULL;
    ui_DirectionSelect0 = NULL;
    uic_DirectionSelectButton2 = NULL;
    ui_DirectionSelectButton2 = NULL;
    uic_DirectionSelectButtonLabel2 = NULL;
    ui_DirectionSelectButtonLabel2 = NULL;
    uic_DirectionSelectButton1 = NULL;
    ui_DirectionSelectButton1 = NULL;
    uic_DirectionSelectButtonLabel1 = NULL;
    ui_DirectionSelectButtonLabel1 = NULL;
    uic_DirectionSelectButton0 = NULL;
    ui_DirectionSelectButton0 = NULL;
    uic_DirectionSelectButtonLabel0 = NULL;
    ui_DirectionSelectButtonLabel0 = NULL;
    uic_DirectionPointer = NULL;
    ui_DirectionPointer = NULL;

}
