// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: test

#ifndef UI_HOMESCREEN_H
#define UI_HOMESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_HomeScreen
extern void ui_HomeScreen_screen_init(void);
extern void ui_HomeScreen_screen_destroy(void);
extern lv_obj_t * ui_HomeScreen;
extern void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label1;
extern void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label2;
extern void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label3;
extern void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label12;
// CUSTOM VARIABLES
extern lv_obj_t * uic_HomeScreen;
extern lv_obj_t * uic_button1;
extern lv_obj_t * uic_label1;
extern lv_obj_t * uic_button2;
extern lv_obj_t * uic_label2;
extern lv_obj_t * uic_button3;
extern lv_obj_t * uic_label3;
extern lv_obj_t * uic_button4;
extern lv_obj_t * uic_label12;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

