// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: test

#ifndef UI_MESSAGEAPPSCREEN_H
#define UI_MESSAGEAPPSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MessageAppScreen
extern void ui_MessageAppScreen_screen_init(void);
extern void ui_MessageAppScreen_screen_destroy(void);
extern lv_obj_t * ui_MessageAppScreen;
extern void ui_event_DropDown3(lv_event_t * e);
extern lv_obj_t * ui_DropDown3;
extern void ui_event_AppBackButton3(lv_event_t * e);
extern lv_obj_t * ui_AppBackButton3;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Send;
extern void ui_event_SendButton(lv_event_t * e);
extern lv_obj_t * ui_SendButton;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_TextArea1;
extern lv_obj_t * ui_Keyboard1;
extern lv_obj_t * ui_Receive;
extern lv_obj_t * ui_ReceiveMessageLabel;
// CUSTOM VARIABLES
extern lv_obj_t * uic_MessageAppScreen;
extern lv_obj_t * uic_DropDown3;
extern lv_obj_t * uic_AppBackButton3;
extern lv_obj_t * uic_Label9;
extern lv_obj_t * uic_Send;
extern lv_obj_t * uic_SendButton;
extern lv_obj_t * uic_Label11;
extern lv_obj_t * uic_TextArea1;
extern lv_obj_t * uic_Keyboard1;
extern lv_obj_t * uic_Receive;
extern lv_obj_t * uic_ReceiveMessageLabel;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

