// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: test

#include "ui.h"

lv_obj_t * uic_ReceiveMessageLabel;
lv_obj_t * uic_Receive;
lv_obj_t * uic_Keyboard1;
lv_obj_t * uic_TextArea1;
lv_obj_t * uic_Label11;
lv_obj_t * uic_SendButton;
lv_obj_t * uic_Send;
lv_obj_t * uic_Label9;
lv_obj_t * uic_AppBackButton3;
lv_obj_t * uic_DropDown3;
lv_obj_t * uic_MessageAppScreen;
lv_obj_t * ui_MessageAppScreen = NULL;
lv_obj_t * ui_DropDown3 = NULL;
lv_obj_t * ui_AppBackButton3 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_Send = NULL;
lv_obj_t * ui_SendButton = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_TextArea1 = NULL;
lv_obj_t * ui_Keyboard1 = NULL;
lv_obj_t * ui_Receive = NULL;
lv_obj_t * ui_ReceiveMessageLabel = NULL;
// event funtions
void ui_event_DropDown3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ui_message_app_dropdown_func(e);
        ui_app_clear_settings_func(e);
    }
}

void ui_event_AppBackButton3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_HomeScreen, LV_SCR_LOAD_ANIM_FADE_ON, 10, 0, &ui_HomeScreen_screen_init);
        ui_app_clear_settings_func(e);
    }
}

void ui_event_SendButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_message_app_send_button_func(e);
    }
}

// build funtions

void ui_MessageAppScreen_screen_init(void)
{
    ui_MessageAppScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MessageAppScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MessageAppScreen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MessageAppScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DropDown3 = lv_dropdown_create(ui_MessageAppScreen);
    lv_dropdown_set_dir(ui_DropDown3, LV_DIR_TOP);
    lv_dropdown_set_options(ui_DropDown3, "Send\nReceive");
    lv_obj_set_width(ui_DropDown3, 248);
    lv_obj_set_height(ui_DropDown3, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_x(ui_DropDown3, 2);
    lv_obj_set_y(ui_DropDown3, 3);
    lv_obj_add_flag(ui_DropDown3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_AppBackButton3 = lv_btn_create(ui_MessageAppScreen);
    lv_obj_set_width(ui_AppBackButton3, 60);
    lv_obj_set_height(ui_AppBackButton3, 35);
    lv_obj_set_x(ui_AppBackButton3, 257);
    lv_obj_set_y(ui_AppBackButton3, 3);
    lv_obj_add_flag(ui_AppBackButton3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_AppBackButton3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AppBackButton3, lv_color_hex(0xFF4F4F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AppBackButton3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_AppBackButton3);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "BACK");

    ui_Send = lv_obj_create(ui_MessageAppScreen);
    lv_obj_set_width(ui_Send, 320);
    lv_obj_set_height(ui_Send, 194);
    lv_obj_set_x(ui_Send, 0);
    lv_obj_set_y(ui_Send, 46);
    lv_obj_clear_flag(ui_Send, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Send, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Send, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Send, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Send, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SendButton = lv_btn_create(ui_Send);
    lv_obj_set_width(ui_SendButton, 60);
    lv_obj_set_height(ui_SendButton, 52);
    lv_obj_set_x(ui_SendButton, -12);
    lv_obj_set_y(ui_SendButton, -15);
    lv_obj_add_flag(ui_SendButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SendButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SendButton, lv_color_hex(0x2DA041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SendButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_SendButton);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "SEND");

    ui_TextArea1 = lv_textarea_create(ui_Send);
    lv_obj_set_width(ui_TextArea1, 247);
    lv_obj_set_height(ui_TextArea1, 52);
    lv_obj_set_x(ui_TextArea1, 12);
    lv_obj_set_y(ui_TextArea1, -15);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_TOP_RIGHT);
    lv_textarea_set_placeholder_text(ui_TextArea1, "Placeholder...");

    ui_Keyboard1 = lv_keyboard_create(ui_Send);
    lv_obj_set_width(ui_Keyboard1, 314);
    lv_obj_set_height(ui_Keyboard1, 140);
    lv_obj_set_x(ui_Keyboard1, 0);
    lv_obj_set_y(ui_Keyboard1, 15);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_BOTTOM_MID);

    ui_Receive = lv_obj_create(ui_MessageAppScreen);
    lv_obj_set_width(ui_Receive, 314);
    lv_obj_set_height(ui_Receive, 191);
    lv_obj_set_x(ui_Receive, 3);
    lv_obj_set_y(ui_Receive, 46);
    lv_obj_add_flag(ui_Receive, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_ReceiveMessageLabel = lv_label_create(ui_Receive);
    lv_obj_set_width(ui_ReceiveMessageLabel, lv_pct(100));
    lv_obj_set_height(ui_ReceiveMessageLabel, LV_SIZE_CONTENT);    /// 10
    lv_label_set_text(ui_ReceiveMessageLabel, "");
    lv_obj_clear_flag(ui_ReceiveMessageLabel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_DropDown3, ui_event_DropDown3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_AppBackButton3, ui_event_AppBackButton3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SendButton, ui_event_SendButton, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard1, ui_TextArea1);
    uic_MessageAppScreen = ui_MessageAppScreen;
    uic_DropDown3 = ui_DropDown3;
    uic_AppBackButton3 = ui_AppBackButton3;
    uic_Label9 = ui_Label9;
    uic_Send = ui_Send;
    uic_SendButton = ui_SendButton;
    uic_Label11 = ui_Label11;
    uic_TextArea1 = ui_TextArea1;
    uic_Keyboard1 = ui_Keyboard1;
    uic_Receive = ui_Receive;
    uic_ReceiveMessageLabel = ui_ReceiveMessageLabel;

}

void ui_MessageAppScreen_screen_destroy(void)
{
    if(ui_MessageAppScreen) lv_obj_del(ui_MessageAppScreen);

    // NULL screen variables
    uic_MessageAppScreen = NULL;
    ui_MessageAppScreen = NULL;
    uic_DropDown3 = NULL;
    ui_DropDown3 = NULL;
    uic_AppBackButton3 = NULL;
    ui_AppBackButton3 = NULL;
    uic_Label9 = NULL;
    ui_Label9 = NULL;
    uic_Send = NULL;
    ui_Send = NULL;
    uic_SendButton = NULL;
    ui_SendButton = NULL;
    uic_Label11 = NULL;
    ui_Label11 = NULL;
    uic_TextArea1 = NULL;
    ui_TextArea1 = NULL;
    uic_Keyboard1 = NULL;
    ui_Keyboard1 = NULL;
    uic_Receive = NULL;
    ui_Receive = NULL;
    uic_ReceiveMessageLabel = NULL;
    ui_ReceiveMessageLabel = NULL;

}
