// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: test

#include "ui.h"

lv_obj_t * uic_FreePanel4;
lv_obj_t * uic_Lidar;
lv_obj_t * uic_AngleIndicator3;
lv_obj_t * uic_MeterBlueLabel4;
lv_obj_t * uic_MeterBlueButton4;
lv_obj_t * uic_MeterYellowLabel3;
lv_obj_t * uic_MeterYellowButton3;
lv_obj_t * uic_Meter3;
lv_obj_t * uic_FreePanel3;
lv_obj_t * uic_Goal;
lv_obj_t * uic_AngleIndicator2;
lv_obj_t * uic_MeterLabel2;
lv_obj_t * uic_MeterButton2;
lv_obj_t * uic_Meter2;
lv_obj_t * uic_FreePanel2;
lv_obj_t * uic_Gyro;
lv_obj_t * uic_AngleIndicator1;
lv_obj_t * uic_MeterLabel1;
lv_obj_t * uic_MeterButton1;
lv_obj_t * uic_Meter1;
lv_obj_t * uic_FreePanel1;
lv_obj_t * uic_Line;
lv_obj_t * uic_AngleIndicator0;
lv_obj_t * uic_Meter0Label;
lv_obj_t * uic_MeterButton0;
lv_obj_t * uic_Meter0;
lv_obj_t * uic_FreePanel0;
lv_obj_t * uic_Ball;
lv_obj_t * uic_Label6;
lv_obj_t * uic_AppBackButton2;
lv_obj_t * uic_DropDown2;
lv_obj_t * uic_SensorCheckAppScreen;
lv_obj_t * ui_SensorCheckAppScreen = NULL;
lv_obj_t * ui_DropDown2 = NULL;
lv_obj_t * ui_AppBackButton2 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Ball = NULL;
lv_obj_t * ui_FreePanel0 = NULL;
lv_obj_t * ui_Meter0 = NULL;
lv_obj_t * ui_MeterButton0 = NULL;
lv_obj_t * ui_Meter0Label = NULL;
lv_obj_t * ui_AngleIndicator0 = NULL;
lv_obj_t * ui_Line = NULL;
lv_obj_t * ui_FreePanel1 = NULL;
lv_obj_t * ui_Meter1 = NULL;
lv_obj_t * ui_MeterButton1 = NULL;
lv_obj_t * ui_MeterLabel1 = NULL;
lv_obj_t * ui_AngleIndicator1 = NULL;
lv_obj_t * ui_Gyro = NULL;
lv_obj_t * ui_FreePanel2 = NULL;
lv_obj_t * ui_Meter2 = NULL;
lv_obj_t * ui_MeterButton2 = NULL;
lv_obj_t * ui_MeterLabel2 = NULL;
lv_obj_t * ui_AngleIndicator2 = NULL;
lv_obj_t * ui_Goal = NULL;
lv_obj_t * ui_FreePanel3 = NULL;
lv_obj_t * ui_Meter3 = NULL;
lv_obj_t * ui_MeterYellowButton3 = NULL;
lv_obj_t * ui_MeterYellowLabel3 = NULL;
lv_obj_t * ui_MeterBlueButton4 = NULL;
lv_obj_t * ui_MeterBlueLabel4 = NULL;
lv_obj_t * ui_AngleIndicator3 = NULL;
lv_obj_t * ui_Lidar = NULL;
lv_obj_t * ui_FreePanel4 = NULL;
// event funtions
void ui_event_DropDown2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ui_sensor_check_app_dropdown_func(e);
        ui_app_clear_settings_func(e);
    }
}

void ui_event_AppBackButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_HomeScreen, LV_SCR_LOAD_ANIM_FADE_ON, 10, 0, &ui_HomeScreen_screen_init);
        ui_app_clear_settings_func(e);
    }
}

void ui_event_MeterButton0(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_DirectionSelectButton4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_DirectionSelectButton3, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_MeterButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_DirectionSelectButton4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_DirectionSelectButton3, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_MeterButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_DirectionSelectButton4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_DirectionSelectButton3, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_MeterYellowButton3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_MeterBlueButton4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_MeterYellowButton3, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_MeterBlueButton4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_MeterYellowButton3, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_MeterBlueButton4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

// build funtions

void ui_SensorCheckAppScreen_screen_init(void)
{
    ui_SensorCheckAppScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SensorCheckAppScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DropDown2 = lv_dropdown_create(ui_SensorCheckAppScreen);
    lv_dropdown_set_dir(ui_DropDown2, LV_DIR_TOP);
    lv_dropdown_set_options(ui_DropDown2, "Ball\nLine\nGyro\nGoal\nLidar");
    lv_obj_set_width(ui_DropDown2, 248);
    lv_obj_set_height(ui_DropDown2, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_x(ui_DropDown2, 2);
    lv_obj_set_y(ui_DropDown2, 3);
    lv_obj_add_flag(ui_DropDown2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_AppBackButton2 = lv_btn_create(ui_SensorCheckAppScreen);
    lv_obj_set_width(ui_AppBackButton2, 60);
    lv_obj_set_height(ui_AppBackButton2, 35);
    lv_obj_set_x(ui_AppBackButton2, 257);
    lv_obj_set_y(ui_AppBackButton2, 3);
    lv_obj_add_flag(ui_AppBackButton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_AppBackButton2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AppBackButton2, lv_color_hex(0xFF4F4F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AppBackButton2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_AppBackButton2);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "BACK");

    ui_Ball = lv_obj_create(ui_SensorCheckAppScreen);
    lv_obj_set_width(ui_Ball, 314);
    lv_obj_set_height(ui_Ball, 191);
    lv_obj_set_x(ui_Ball, 3);
    lv_obj_set_y(ui_Ball, 46);
    lv_obj_add_flag(ui_Ball, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Ball, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Ball, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Ball, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Ball, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Ball, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FreePanel0 = lv_obj_create(ui_Ball);
    lv_obj_set_width(ui_FreePanel0, 195);
    lv_obj_set_height(ui_FreePanel0, 191);
    lv_obj_set_x(ui_FreePanel0, -15);
    lv_obj_set_y(ui_FreePanel0, -15);
    lv_obj_clear_flag(ui_FreePanel0, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Meter0 = lv_obj_create(ui_Ball);
    lv_obj_set_width(ui_Meter0, 116);
    lv_obj_set_height(ui_Meter0, 116);
    lv_obj_set_x(ui_Meter0, 15);
    lv_obj_set_y(ui_Meter0, -10);
    lv_obj_set_align(ui_Meter0, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_Meter0, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Meter0, 58, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Meter0, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Meter0, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Meter0, lv_color_hex(0xD5D2D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Meter0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Meter0, 7, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MeterButton0 = lv_btn_create(ui_Meter0);
    lv_obj_set_width(ui_MeterButton0, 74);
    lv_obj_set_height(ui_MeterButton0, 74);
    lv_obj_set_align(ui_MeterButton0, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MeterButton0, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MeterButton0, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MeterButton0, lv_color_hex(0xD5D2D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MeterButton0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_MeterButton0, 0, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_color(ui_MeterButton0, lv_color_hex(0xD3D904), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_opa(ui_MeterButton0, 255, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_radius(ui_MeterButton0, 0, LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_bg_color(ui_MeterButton0, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_bg_opa(ui_MeterButton0, 255, LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_radius(ui_MeterButton0, 0, LV_PART_MAIN | LV_STATE_USER_3);
    lv_obj_set_style_bg_color(ui_MeterButton0, lv_color_hex(0x545454), LV_PART_MAIN | LV_STATE_USER_3);
    lv_obj_set_style_bg_opa(ui_MeterButton0, 255, LV_PART_MAIN | LV_STATE_USER_3);

    ui_Meter0Label = lv_label_create(ui_MeterButton0);
    lv_obj_set_width(ui_Meter0Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Meter0Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Meter0Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Meter0Label, "30");

    ui_AngleIndicator0 = lv_obj_create(ui_Ball);
    lv_obj_set_width(ui_AngleIndicator0, 16);
    lv_obj_set_height(ui_AngleIndicator0, 16);
    lv_obj_set_x(ui_AngleIndicator0, -35);
    lv_obj_set_y(ui_AngleIndicator0, -14);
    lv_obj_set_align(ui_AngleIndicator0, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_AngleIndicator0, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_AngleIndicator0, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AngleIndicator0, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AngleIndicator0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_AngleIndicator0, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_AngleIndicator0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_AngleIndicator0, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Line = lv_obj_create(ui_SensorCheckAppScreen);
    lv_obj_set_width(ui_Line, 314);
    lv_obj_set_height(ui_Line, 191);
    lv_obj_set_x(ui_Line, 3);
    lv_obj_set_y(ui_Line, 46);
    lv_obj_clear_flag(ui_Line, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Line, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Line, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Line, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Line, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FreePanel1 = lv_obj_create(ui_Line);
    lv_obj_set_width(ui_FreePanel1, 195);
    lv_obj_set_height(ui_FreePanel1, 191);
    lv_obj_set_x(ui_FreePanel1, -15);
    lv_obj_set_y(ui_FreePanel1, -15);
    lv_obj_clear_flag(ui_FreePanel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Meter1 = lv_obj_create(ui_Line);
    lv_obj_set_width(ui_Meter1, 116);
    lv_obj_set_height(ui_Meter1, 116);
    lv_obj_set_x(ui_Meter1, 15);
    lv_obj_set_y(ui_Meter1, -10);
    lv_obj_set_align(ui_Meter1, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_Meter1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Meter1, 58, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Meter1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Meter1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Meter1, lv_color_hex(0xD5D2D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Meter1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Meter1, 7, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MeterButton1 = lv_btn_create(ui_Meter1);
    lv_obj_set_width(ui_MeterButton1, 74);
    lv_obj_set_height(ui_MeterButton1, 74);
    lv_obj_set_align(ui_MeterButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MeterButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MeterButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MeterButton1, lv_color_hex(0xD5D2D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MeterButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_MeterButton1, 0, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_color(ui_MeterButton1, lv_color_hex(0xD3D904), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_opa(ui_MeterButton1, 255, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_radius(ui_MeterButton1, 0, LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_bg_color(ui_MeterButton1, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_bg_opa(ui_MeterButton1, 255, LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_radius(ui_MeterButton1, 0, LV_PART_MAIN | LV_STATE_USER_3);
    lv_obj_set_style_bg_color(ui_MeterButton1, lv_color_hex(0x545454), LV_PART_MAIN | LV_STATE_USER_3);
    lv_obj_set_style_bg_opa(ui_MeterButton1, 255, LV_PART_MAIN | LV_STATE_USER_3);

    ui_MeterLabel1 = lv_label_create(ui_MeterButton1);
    lv_obj_set_width(ui_MeterLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MeterLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MeterLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MeterLabel1, "30");

    ui_AngleIndicator1 = lv_obj_create(ui_Line);
    lv_obj_set_width(ui_AngleIndicator1, 16);
    lv_obj_set_height(ui_AngleIndicator1, 16);
    lv_obj_set_x(ui_AngleIndicator1, -35);
    lv_obj_set_y(ui_AngleIndicator1, -14);
    lv_obj_set_align(ui_AngleIndicator1, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_AngleIndicator1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_AngleIndicator1, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AngleIndicator1, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AngleIndicator1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_AngleIndicator1, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_AngleIndicator1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_AngleIndicator1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Gyro = lv_obj_create(ui_SensorCheckAppScreen);
    lv_obj_set_width(ui_Gyro, 314);
    lv_obj_set_height(ui_Gyro, 191);
    lv_obj_set_x(ui_Gyro, 3);
    lv_obj_set_y(ui_Gyro, 46);
    lv_obj_add_flag(ui_Gyro, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Gyro, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Gyro, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Gyro, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Gyro, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Gyro, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FreePanel2 = lv_obj_create(ui_Gyro);
    lv_obj_set_width(ui_FreePanel2, 195);
    lv_obj_set_height(ui_FreePanel2, 191);
    lv_obj_set_x(ui_FreePanel2, -15);
    lv_obj_set_y(ui_FreePanel2, -15);
    lv_obj_clear_flag(ui_FreePanel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Meter2 = lv_obj_create(ui_Gyro);
    lv_obj_set_width(ui_Meter2, 116);
    lv_obj_set_height(ui_Meter2, 116);
    lv_obj_set_x(ui_Meter2, 15);
    lv_obj_set_y(ui_Meter2, -10);
    lv_obj_set_align(ui_Meter2, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_Meter2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Meter2, 58, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Meter2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Meter2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Meter2, lv_color_hex(0xD5D2D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Meter2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Meter2, 7, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MeterButton2 = lv_btn_create(ui_Meter2);
    lv_obj_set_width(ui_MeterButton2, 74);
    lv_obj_set_height(ui_MeterButton2, 74);
    lv_obj_set_align(ui_MeterButton2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MeterButton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MeterButton2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MeterButton2, lv_color_hex(0xD5D2D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MeterButton2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_MeterButton2, 0, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_color(ui_MeterButton2, lv_color_hex(0xD3D904), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_opa(ui_MeterButton2, 255, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_radius(ui_MeterButton2, 0, LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_bg_color(ui_MeterButton2, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_bg_opa(ui_MeterButton2, 255, LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_radius(ui_MeterButton2, 0, LV_PART_MAIN | LV_STATE_USER_3);
    lv_obj_set_style_bg_color(ui_MeterButton2, lv_color_hex(0x545454), LV_PART_MAIN | LV_STATE_USER_3);
    lv_obj_set_style_bg_opa(ui_MeterButton2, 255, LV_PART_MAIN | LV_STATE_USER_3);

    ui_MeterLabel2 = lv_label_create(ui_MeterButton2);
    lv_obj_set_width(ui_MeterLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MeterLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MeterLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MeterLabel2, "30");

    ui_AngleIndicator2 = lv_obj_create(ui_Gyro);
    lv_obj_set_width(ui_AngleIndicator2, 16);
    lv_obj_set_height(ui_AngleIndicator2, 16);
    lv_obj_set_x(ui_AngleIndicator2, -35);
    lv_obj_set_y(ui_AngleIndicator2, -14);
    lv_obj_set_align(ui_AngleIndicator2, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_AngleIndicator2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_AngleIndicator2, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AngleIndicator2, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AngleIndicator2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_AngleIndicator2, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_AngleIndicator2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_AngleIndicator2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Goal = lv_obj_create(ui_SensorCheckAppScreen);
    lv_obj_set_width(ui_Goal, 314);
    lv_obj_set_height(ui_Goal, 191);
    lv_obj_set_x(ui_Goal, 3);
    lv_obj_set_y(ui_Goal, 46);
    lv_obj_add_flag(ui_Goal, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Goal, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Goal, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Goal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Goal, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Goal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FreePanel3 = lv_obj_create(ui_Goal);
    lv_obj_set_width(ui_FreePanel3, 195);
    lv_obj_set_height(ui_FreePanel3, 191);
    lv_obj_set_x(ui_FreePanel3, -15);
    lv_obj_set_y(ui_FreePanel3, -15);
    lv_obj_clear_flag(ui_FreePanel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Meter3 = lv_obj_create(ui_Goal);
    lv_obj_set_width(ui_Meter3, 116);
    lv_obj_set_height(ui_Meter3, 116);
    lv_obj_set_x(ui_Meter3, 15);
    lv_obj_set_y(ui_Meter3, -10);
    lv_obj_set_align(ui_Meter3, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_Meter3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Meter3, 58, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Meter3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Meter3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Meter3, lv_color_hex(0xD5D2D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Meter3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Meter3, 7, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MeterYellowButton3 = lv_btn_create(ui_Meter3);
    lv_obj_set_width(ui_MeterYellowButton3, 74);
    lv_obj_set_height(ui_MeterYellowButton3, 74);
    lv_obj_set_align(ui_MeterYellowButton3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MeterYellowButton3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MeterYellowButton3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MeterYellowButton3, lv_color_hex(0xE7DF29), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MeterYellowButton3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_MeterYellowButton3, 0, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_color(ui_MeterYellowButton3, lv_color_hex(0xD3D904), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_opa(ui_MeterYellowButton3, 255, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_radius(ui_MeterYellowButton3, 0, LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_bg_color(ui_MeterYellowButton3, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_bg_opa(ui_MeterYellowButton3, 255, LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_radius(ui_MeterYellowButton3, 0, LV_PART_MAIN | LV_STATE_USER_3);
    lv_obj_set_style_bg_color(ui_MeterYellowButton3, lv_color_hex(0x545454), LV_PART_MAIN | LV_STATE_USER_3);
    lv_obj_set_style_bg_opa(ui_MeterYellowButton3, 255, LV_PART_MAIN | LV_STATE_USER_3);

    ui_MeterYellowLabel3 = lv_label_create(ui_MeterYellowButton3);
    lv_obj_set_width(ui_MeterYellowLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MeterYellowLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MeterYellowLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MeterYellowLabel3, "30");

    ui_MeterBlueButton4 = lv_btn_create(ui_Meter3);
    lv_obj_set_width(ui_MeterBlueButton4, 74);
    lv_obj_set_height(ui_MeterBlueButton4, 74);
    lv_obj_set_align(ui_MeterBlueButton4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MeterBlueButton4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MeterBlueButton4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MeterBlueButton4, 0, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_color(ui_MeterBlueButton4, lv_color_hex(0xD3D904), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_opa(ui_MeterBlueButton4, 255, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_radius(ui_MeterBlueButton4, 0, LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_bg_color(ui_MeterBlueButton4, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_bg_opa(ui_MeterBlueButton4, 255, LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_radius(ui_MeterBlueButton4, 0, LV_PART_MAIN | LV_STATE_USER_3);
    lv_obj_set_style_bg_color(ui_MeterBlueButton4, lv_color_hex(0x545454), LV_PART_MAIN | LV_STATE_USER_3);
    lv_obj_set_style_bg_opa(ui_MeterBlueButton4, 255, LV_PART_MAIN | LV_STATE_USER_3);

    ui_MeterBlueLabel4 = lv_label_create(ui_MeterBlueButton4);
    lv_obj_set_width(ui_MeterBlueLabel4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MeterBlueLabel4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MeterBlueLabel4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MeterBlueLabel4, "30");

    ui_AngleIndicator3 = lv_obj_create(ui_Goal);
    lv_obj_set_width(ui_AngleIndicator3, 16);
    lv_obj_set_height(ui_AngleIndicator3, 16);
    lv_obj_set_x(ui_AngleIndicator3, -35);
    lv_obj_set_y(ui_AngleIndicator3, -14);
    lv_obj_set_align(ui_AngleIndicator3, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_AngleIndicator3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_AngleIndicator3, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AngleIndicator3, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AngleIndicator3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_AngleIndicator3, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_AngleIndicator3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_AngleIndicator3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Lidar = lv_obj_create(ui_SensorCheckAppScreen);
    lv_obj_set_width(ui_Lidar, 314);
    lv_obj_set_height(ui_Lidar, 191);
    lv_obj_set_x(ui_Lidar, 3);
    lv_obj_set_y(ui_Lidar, 46);
    lv_obj_add_flag(ui_Lidar, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Lidar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Lidar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Lidar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Lidar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Lidar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FreePanel4 = lv_obj_create(ui_Lidar);
    lv_obj_set_width(ui_FreePanel4, 314);
    lv_obj_set_height(ui_FreePanel4, 191);
    lv_obj_set_x(ui_FreePanel4, -15);
    lv_obj_set_y(ui_FreePanel4, -15);
    lv_obj_clear_flag(ui_FreePanel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_DropDown2, ui_event_DropDown2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_AppBackButton2, ui_event_AppBackButton2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MeterButton0, ui_event_MeterButton0, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MeterButton1, ui_event_MeterButton1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MeterButton2, ui_event_MeterButton2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MeterYellowButton3, ui_event_MeterYellowButton3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MeterBlueButton4, ui_event_MeterBlueButton4, LV_EVENT_ALL, NULL);
    uic_SensorCheckAppScreen = ui_SensorCheckAppScreen;
    uic_DropDown2 = ui_DropDown2;
    uic_AppBackButton2 = ui_AppBackButton2;
    uic_Label6 = ui_Label6;
    uic_Ball = ui_Ball;
    uic_FreePanel0 = ui_FreePanel0;
    uic_Meter0 = ui_Meter0;
    uic_MeterButton0 = ui_MeterButton0;
    uic_Meter0Label = ui_Meter0Label;
    uic_AngleIndicator0 = ui_AngleIndicator0;
    uic_Line = ui_Line;
    uic_FreePanel1 = ui_FreePanel1;
    uic_Meter1 = ui_Meter1;
    uic_MeterButton1 = ui_MeterButton1;
    uic_MeterLabel1 = ui_MeterLabel1;
    uic_AngleIndicator1 = ui_AngleIndicator1;
    uic_Gyro = ui_Gyro;
    uic_FreePanel2 = ui_FreePanel2;
    uic_Meter2 = ui_Meter2;
    uic_MeterButton2 = ui_MeterButton2;
    uic_MeterLabel2 = ui_MeterLabel2;
    uic_AngleIndicator2 = ui_AngleIndicator2;
    uic_Goal = ui_Goal;
    uic_FreePanel3 = ui_FreePanel3;
    uic_Meter3 = ui_Meter3;
    uic_MeterYellowButton3 = ui_MeterYellowButton3;
    uic_MeterYellowLabel3 = ui_MeterYellowLabel3;
    uic_MeterBlueButton4 = ui_MeterBlueButton4;
    uic_MeterBlueLabel4 = ui_MeterBlueLabel4;
    uic_AngleIndicator3 = ui_AngleIndicator3;
    uic_Lidar = ui_Lidar;
    uic_FreePanel4 = ui_FreePanel4;

}

void ui_SensorCheckAppScreen_screen_destroy(void)
{
    if(ui_SensorCheckAppScreen) lv_obj_del(ui_SensorCheckAppScreen);

    // NULL screen variables
    uic_SensorCheckAppScreen = NULL;
    ui_SensorCheckAppScreen = NULL;
    uic_DropDown2 = NULL;
    ui_DropDown2 = NULL;
    uic_AppBackButton2 = NULL;
    ui_AppBackButton2 = NULL;
    uic_Label6 = NULL;
    ui_Label6 = NULL;
    uic_Ball = NULL;
    ui_Ball = NULL;
    uic_FreePanel0 = NULL;
    ui_FreePanel0 = NULL;
    uic_Meter0 = NULL;
    ui_Meter0 = NULL;
    uic_MeterButton0 = NULL;
    ui_MeterButton0 = NULL;
    uic_Meter0Label = NULL;
    ui_Meter0Label = NULL;
    uic_AngleIndicator0 = NULL;
    ui_AngleIndicator0 = NULL;
    uic_Line = NULL;
    ui_Line = NULL;
    uic_FreePanel1 = NULL;
    ui_FreePanel1 = NULL;
    uic_Meter1 = NULL;
    ui_Meter1 = NULL;
    uic_MeterButton1 = NULL;
    ui_MeterButton1 = NULL;
    uic_MeterLabel1 = NULL;
    ui_MeterLabel1 = NULL;
    uic_AngleIndicator1 = NULL;
    ui_AngleIndicator1 = NULL;
    uic_Gyro = NULL;
    ui_Gyro = NULL;
    uic_FreePanel2 = NULL;
    ui_FreePanel2 = NULL;
    uic_Meter2 = NULL;
    ui_Meter2 = NULL;
    uic_MeterButton2 = NULL;
    ui_MeterButton2 = NULL;
    uic_MeterLabel2 = NULL;
    ui_MeterLabel2 = NULL;
    uic_AngleIndicator2 = NULL;
    ui_AngleIndicator2 = NULL;
    uic_Goal = NULL;
    ui_Goal = NULL;
    uic_FreePanel3 = NULL;
    ui_FreePanel3 = NULL;
    uic_Meter3 = NULL;
    ui_Meter3 = NULL;
    uic_MeterYellowButton3 = NULL;
    ui_MeterYellowButton3 = NULL;
    uic_MeterYellowLabel3 = NULL;
    ui_MeterYellowLabel3 = NULL;
    uic_MeterBlueButton4 = NULL;
    ui_MeterBlueButton4 = NULL;
    uic_MeterBlueLabel4 = NULL;
    ui_MeterBlueLabel4 = NULL;
    uic_AngleIndicator3 = NULL;
    ui_AngleIndicator3 = NULL;
    uic_Lidar = NULL;
    ui_Lidar = NULL;
    uic_FreePanel4 = NULL;
    ui_FreePanel4 = NULL;

}
