// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: test

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_action_select_app_dropdown_func(lv_event_t * e);
void ui_app_clear_settings_func(lv_event_t * e);
void ui_test_app_dropdown_func(lv_event_t * e);
void ui_sensor_check_app_dropdown_func(lv_event_t * e);
void ui_message_app_dropdown_func(lv_event_t * e);
void ui_message_app_send_button_func(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
