// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: test

#ifndef UI_SENSORCHECKAPPSCREEN_H
#define UI_SENSORCHECKAPPSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SensorCheckAppScreen
extern void ui_SensorCheckAppScreen_screen_init(void);
extern void ui_SensorCheckAppScreen_screen_destroy(void);
extern lv_obj_t * ui_SensorCheckAppScreen;
extern void ui_event_DropDown2(lv_event_t * e);
extern lv_obj_t * ui_DropDown2;
extern void ui_event_AppBackButton2(lv_event_t * e);
extern lv_obj_t * ui_AppBackButton2;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Ball;
extern lv_obj_t * ui_FreePanel0;
extern lv_obj_t * ui_Meter0;
extern void ui_event_MeterButton0(lv_event_t * e);
extern lv_obj_t * ui_MeterButton0;
extern lv_obj_t * ui_Meter0Label;
extern lv_obj_t * ui_AngleIndicator0;
extern lv_obj_t * ui_Line;
extern lv_obj_t * ui_FreePanel1;
extern lv_obj_t * ui_Meter1;
extern void ui_event_MeterButton1(lv_event_t * e);
extern lv_obj_t * ui_MeterButton1;
extern lv_obj_t * ui_MeterLabel1;
extern lv_obj_t * ui_AngleIndicator1;
extern lv_obj_t * ui_Gyro;
extern lv_obj_t * ui_FreePanel2;
extern lv_obj_t * ui_Meter2;
extern void ui_event_MeterButton2(lv_event_t * e);
extern lv_obj_t * ui_MeterButton2;
extern lv_obj_t * ui_MeterLabel2;
extern lv_obj_t * ui_AngleIndicator2;
extern lv_obj_t * ui_Goal;
extern lv_obj_t * ui_FreePanel3;
extern lv_obj_t * ui_Meter3;
extern void ui_event_MeterYellowButton3(lv_event_t * e);
extern lv_obj_t * ui_MeterYellowButton3;
extern lv_obj_t * ui_MeterYellowLabel3;
extern void ui_event_MeterBlueButton4(lv_event_t * e);
extern lv_obj_t * ui_MeterBlueButton4;
extern lv_obj_t * ui_MeterBlueLabel4;
extern lv_obj_t * ui_AngleIndicator3;
extern lv_obj_t * ui_Lidar;
extern lv_obj_t * ui_FreePanel4;
// CUSTOM VARIABLES
extern lv_obj_t * uic_SensorCheckAppScreen;
extern lv_obj_t * uic_DropDown2;
extern lv_obj_t * uic_AppBackButton2;
extern lv_obj_t * uic_Label6;
extern lv_obj_t * uic_Ball;
extern lv_obj_t * uic_FreePanel0;
extern lv_obj_t * uic_Meter0;
extern lv_obj_t * uic_MeterButton0;
extern lv_obj_t * uic_Meter0Label;
extern lv_obj_t * uic_AngleIndicator0;
extern lv_obj_t * uic_Line;
extern lv_obj_t * uic_FreePanel1;
extern lv_obj_t * uic_Meter1;
extern lv_obj_t * uic_MeterButton1;
extern lv_obj_t * uic_MeterLabel1;
extern lv_obj_t * uic_AngleIndicator1;
extern lv_obj_t * uic_Gyro;
extern lv_obj_t * uic_FreePanel2;
extern lv_obj_t * uic_Meter2;
extern lv_obj_t * uic_MeterButton2;
extern lv_obj_t * uic_MeterLabel2;
extern lv_obj_t * uic_AngleIndicator2;
extern lv_obj_t * uic_Goal;
extern lv_obj_t * uic_FreePanel3;
extern lv_obj_t * uic_Meter3;
extern lv_obj_t * uic_MeterYellowButton3;
extern lv_obj_t * uic_MeterYellowLabel3;
extern lv_obj_t * uic_MeterBlueButton4;
extern lv_obj_t * uic_MeterBlueLabel4;
extern lv_obj_t * uic_AngleIndicator3;
extern lv_obj_t * uic_Lidar;
extern lv_obj_t * uic_FreePanel4;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

