// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Action = NULL;
lv_obj_t * ui_ActionTopContainer = NULL;
lv_obj_t * ui_ActionDropdown = NULL;
lv_obj_t * ui_ActionBackButton = NULL;
lv_obj_t * ui_ActionBackLabel = NULL;
lv_obj_t * ui_ActionMidContainer = NULL;
lv_obj_t * ui_ActionLeverContainer = NULL;
lv_obj_t * ui_ActionLeverRunButton = NULL;
lv_obj_t * ui_ActionLeverRunLabel = NULL;
lv_obj_t * ui_ActionLeverIdleButton = NULL;
lv_obj_t * ui_ActionLeverIdleLabel = NULL;
lv_obj_t * ui_ActionMeterContainer = NULL;
lv_obj_t * ui_ActionMeterPanel = NULL;
lv_obj_t * ui_ActionMeterButton = NULL;
lv_obj_t * ui_ActionMeterPointorPanel = NULL;
lv_obj_t * ui_ActionConfigContainer = NULL;
lv_obj_t * ui_ActionConfigCheckbox1 = NULL;
lv_obj_t * ui_ActionConfigCheckbox2 = NULL;
lv_obj_t * ui_ActionConfigCheckbox3 = NULL;
lv_obj_t * ui_ActionConfigCheckbox4 = NULL;
lv_obj_t * ui_ActionDebugPanel = NULL;
lv_obj_t * ui_ActionDebugLabel = NULL;
// event funtions
void ui_event_Action(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        action_loaded_event(e);
    }
}

void ui_event_ActionDropdown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        action_dropdown_value_changed_event(e);
    }
}

void ui_event_ActionBackButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_HomeScreen, LV_SCR_LOAD_ANIM_FADE_ON, 10, 0, &ui_HomeScreen_screen_init);
    }
}

void ui_event_ActionLeverRunButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ActionLeverIdleButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_ActionLeverRunButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

void ui_event_ActionLeverIdleButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ActionLeverIdleButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_ActionLeverRunButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

void ui_event_ActionMeterButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        action_meter_switch_event(e);
    }
}

// build funtions

void ui_Action_screen_init(void)
{
    ui_Action = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Action, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ActionTopContainer = lv_obj_create(ui_Action);
    lv_obj_remove_style_all(ui_ActionTopContainer);
    lv_obj_set_width(ui_ActionTopContainer, 320);
    lv_obj_set_height(ui_ActionTopContainer, 40);
    lv_obj_clear_flag(ui_ActionTopContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ActionDropdown = lv_dropdown_create(ui_ActionTopContainer);
    lv_dropdown_set_options(ui_ActionDropdown, "Offense\nDefense\nRadioControl");
    lv_obj_set_width(ui_ActionDropdown, 258);
    lv_obj_set_height(ui_ActionDropdown, 38);
    lv_obj_set_x(ui_ActionDropdown, 1);
    lv_obj_set_y(ui_ActionDropdown, 1);
    lv_obj_add_flag(ui_ActionDropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_ActionBackButton = lv_btn_create(ui_ActionTopContainer);
    lv_obj_set_width(ui_ActionBackButton, 58);
    lv_obj_set_height(ui_ActionBackButton, 38);
    lv_obj_set_x(ui_ActionBackButton, 261);
    lv_obj_set_y(ui_ActionBackButton, 1);
    lv_obj_add_flag(ui_ActionBackButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ActionBackButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ActionBackButton, lv_color_hex(0xFF3333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ActionBackButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ActionBackButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ActionBackButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_ActionBackButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_ActionBackButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ActionBackLabel = lv_label_create(ui_ActionBackButton);
    lv_obj_set_width(ui_ActionBackLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ActionBackLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ActionBackLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ActionBackLabel, "Back");
    lv_obj_set_style_text_color(ui_ActionBackLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ActionBackLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_ActionBackLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_ActionBackLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ActionBackLabel, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_ActionBackLabel, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ActionBackLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ActionMidContainer = lv_obj_create(ui_Action);
    lv_obj_remove_style_all(ui_ActionMidContainer);
    lv_obj_set_width(ui_ActionMidContainer, 320);
    lv_obj_set_height(ui_ActionMidContainer, 200);
    lv_obj_set_x(ui_ActionMidContainer, 0);
    lv_obj_set_y(ui_ActionMidContainer, 40);
    lv_obj_clear_flag(ui_ActionMidContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ActionLeverContainer = lv_obj_create(ui_ActionMidContainer);
    lv_obj_remove_style_all(ui_ActionLeverContainer);
    lv_obj_set_width(ui_ActionLeverContainer, 100);
    lv_obj_set_height(ui_ActionLeverContainer, 100);
    lv_obj_set_x(ui_ActionLeverContainer, 1);
    lv_obj_set_y(ui_ActionLeverContainer, 1);
    lv_obj_clear_flag(ui_ActionLeverContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ActionLeverRunButton = lv_btn_create(ui_ActionLeverContainer);
    lv_obj_set_width(ui_ActionLeverRunButton, 98);
    lv_obj_set_height(ui_ActionLeverRunButton, 98);
    lv_obj_set_align(ui_ActionLeverRunButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ActionLeverRunButton, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ActionLeverRunButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ActionLeverRunButton, lv_color_hex(0x2DA041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ActionLeverRunButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ActionLeverRunButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ActionLeverRunButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_ActionLeverRunButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_ActionLeverRunButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ActionLeverRunLabel = lv_label_create(ui_ActionLeverRunButton);
    lv_obj_set_width(ui_ActionLeverRunLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ActionLeverRunLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ActionLeverRunLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ActionLeverRunLabel, "Run");
    lv_obj_set_style_text_color(ui_ActionLeverRunLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ActionLeverRunLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_ActionLeverRunLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_ActionLeverRunLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ActionLeverRunLabel, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_ActionLeverRunLabel, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ActionLeverRunLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ActionLeverIdleButton = lv_btn_create(ui_ActionLeverContainer);
    lv_obj_set_width(ui_ActionLeverIdleButton, 98);
    lv_obj_set_height(ui_ActionLeverIdleButton, 98);
    lv_obj_set_align(ui_ActionLeverIdleButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ActionLeverIdleButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ActionLeverIdleButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ActionLeverIdleButton, lv_color_hex(0x565656), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ActionLeverIdleButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ActionLeverIdleButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ActionLeverIdleButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_ActionLeverIdleButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_ActionLeverIdleButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ActionLeverIdleLabel = lv_label_create(ui_ActionLeverIdleButton);
    lv_obj_set_width(ui_ActionLeverIdleLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ActionLeverIdleLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ActionLeverIdleLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ActionLeverIdleLabel, "Idle");
    lv_obj_set_style_text_color(ui_ActionLeverIdleLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ActionLeverIdleLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_ActionLeverIdleLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_ActionLeverIdleLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ActionLeverIdleLabel, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_ActionLeverIdleLabel, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ActionLeverIdleLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ActionMeterContainer = lv_obj_create(ui_ActionMidContainer);
    lv_obj_remove_style_all(ui_ActionMeterContainer);
    lv_obj_set_width(ui_ActionMeterContainer, 100);
    lv_obj_set_height(ui_ActionMeterContainer, 100);
    lv_obj_set_x(ui_ActionMeterContainer, 0);
    lv_obj_set_y(ui_ActionMeterContainer, 1);
    lv_obj_set_align(ui_ActionMeterContainer, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_ActionMeterContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ActionMeterPanel = lv_obj_create(ui_ActionMeterContainer);
    lv_obj_set_width(ui_ActionMeterPanel, 93);
    lv_obj_set_height(ui_ActionMeterPanel, 93);
    lv_obj_set_align(ui_ActionMeterPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ActionMeterPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ActionMeterPanel, 47, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ActionMeterPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ActionMeterPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ActionMeterPanel, lv_color_hex(0x565656), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ActionMeterPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ActionMeterPanel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ActionMeterButton = lv_btn_create(ui_ActionMeterPanel);
    lv_obj_set_width(ui_ActionMeterButton, 70);
    lv_obj_set_height(ui_ActionMeterButton, 70);
    lv_obj_set_align(ui_ActionMeterButton, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_ActionMeterButton, LV_STATE_USER_1);       /// States
    lv_obj_add_flag(ui_ActionMeterButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ActionMeterButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ActionMeterButton, 35, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ActionMeterButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ActionMeterButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_ActionMeterButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_ActionMeterButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ActionMeterButton, lv_color_hex(0xE8E839), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_opa(ui_ActionMeterButton, 255, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_color(ui_ActionMeterButton, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_bg_opa(ui_ActionMeterButton, 255, LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_bg_color(ui_ActionMeterButton, lv_color_hex(0x525552), LV_PART_MAIN | LV_STATE_USER_3);
    lv_obj_set_style_bg_opa(ui_ActionMeterButton, 255, LV_PART_MAIN | LV_STATE_USER_3);

    ui_ActionMeterPointorPanel = lv_obj_create(ui_ActionMeterContainer);
    lv_obj_set_width(ui_ActionMeterPointorPanel, 12);
    lv_obj_set_height(ui_ActionMeterPointorPanel, 12);
    lv_obj_set_x(ui_ActionMeterPointorPanel, 0);
    lv_obj_set_y(ui_ActionMeterPointorPanel, -43);
    lv_obj_set_align(ui_ActionMeterPointorPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ActionMeterPointorPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ActionMeterPointorPanel, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ActionMeterPointorPanel, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ActionMeterPointorPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ActionMeterPointorPanel, lv_color_hex(0x565656), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ActionMeterPointorPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ActionConfigContainer = lv_obj_create(ui_ActionMidContainer);
    lv_obj_remove_style_all(ui_ActionConfigContainer);
    lv_obj_set_width(ui_ActionConfigContainer, 120);
    lv_obj_set_height(ui_ActionConfigContainer, 100);
    lv_obj_set_x(ui_ActionConfigContainer, 106);
    lv_obj_set_y(ui_ActionConfigContainer, 1);
    lv_obj_clear_flag(ui_ActionConfigContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ActionConfigCheckbox1 = lv_checkbox_create(ui_ActionConfigContainer);
    lv_obj_set_height(ui_ActionConfigCheckbox1, 20);
    lv_obj_set_width(ui_ActionConfigCheckbox1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ActionConfigCheckbox1, 2);
    lv_obj_set_y(ui_ActionConfigCheckbox1, 3);
    lv_obj_add_flag(ui_ActionConfigCheckbox1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_ActionConfigCheckbox2 = lv_checkbox_create(ui_ActionConfigContainer);
    lv_obj_set_height(ui_ActionConfigCheckbox2, 20);
    lv_obj_set_width(ui_ActionConfigCheckbox2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ActionConfigCheckbox2, 2);
    lv_obj_set_y(ui_ActionConfigCheckbox2, 28);
    lv_obj_add_flag(ui_ActionConfigCheckbox2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_ActionConfigCheckbox3 = lv_checkbox_create(ui_ActionConfigContainer);
    lv_obj_set_height(ui_ActionConfigCheckbox3, 20);
    lv_obj_set_width(ui_ActionConfigCheckbox3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ActionConfigCheckbox3, 2);
    lv_obj_set_y(ui_ActionConfigCheckbox3, 53);
    lv_obj_add_flag(ui_ActionConfigCheckbox3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_ActionConfigCheckbox4 = lv_checkbox_create(ui_ActionConfigContainer);
    lv_obj_set_height(ui_ActionConfigCheckbox4, 20);
    lv_obj_set_width(ui_ActionConfigCheckbox4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ActionConfigCheckbox4, 2);
    lv_obj_set_y(ui_ActionConfigCheckbox4, 78);
    lv_obj_add_flag(ui_ActionConfigCheckbox4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_ActionDebugPanel = lv_obj_create(ui_ActionMidContainer);
    lv_obj_set_width(ui_ActionDebugPanel, 318);
    lv_obj_set_height(ui_ActionDebugPanel, 96);
    lv_obj_set_x(ui_ActionDebugPanel, 1);
    lv_obj_set_y(ui_ActionDebugPanel, -1);
    lv_obj_set_align(ui_ActionDebugPanel, LV_ALIGN_BOTTOM_LEFT);

    ui_ActionDebugLabel = lv_label_create(ui_ActionDebugPanel);
    lv_obj_set_width(ui_ActionDebugLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ActionDebugLabel, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_ActionDebugLabel,
                      "Communication : true\nGyro : 70 , -45\nBallDeg : 170 , -60\nYellowGoalDeg : 10 , -30\nBlueGoalDeg : -140 , -100\nPosition : (10,60) , (-10,-100)\nPosition : (10,-100)");

    lv_obj_add_event_cb(ui_ActionDropdown, ui_event_ActionDropdown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ActionBackButton, ui_event_ActionBackButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ActionLeverRunButton, ui_event_ActionLeverRunButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ActionLeverIdleButton, ui_event_ActionLeverIdleButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ActionMeterButton, ui_event_ActionMeterButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Action, ui_event_Action, LV_EVENT_ALL, NULL);

}

void ui_Action_screen_destroy(void)
{
    if(ui_Action) lv_obj_del(ui_Action);

    // NULL screen variables
    ui_Action = NULL;
    ui_ActionTopContainer = NULL;
    ui_ActionDropdown = NULL;
    ui_ActionBackButton = NULL;
    ui_ActionBackLabel = NULL;
    ui_ActionMidContainer = NULL;
    ui_ActionLeverContainer = NULL;
    ui_ActionLeverRunButton = NULL;
    ui_ActionLeverRunLabel = NULL;
    ui_ActionLeverIdleButton = NULL;
    ui_ActionLeverIdleLabel = NULL;
    ui_ActionMeterContainer = NULL;
    ui_ActionMeterPanel = NULL;
    ui_ActionMeterButton = NULL;
    ui_ActionMeterPointorPanel = NULL;
    ui_ActionConfigContainer = NULL;
    ui_ActionConfigCheckbox1 = NULL;
    ui_ActionConfigCheckbox2 = NULL;
    ui_ActionConfigCheckbox3 = NULL;
    ui_ActionConfigCheckbox4 = NULL;
    ui_ActionDebugPanel = NULL;
    ui_ActionDebugLabel = NULL;

}
