// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: test

#include "ui.h"

lv_obj_t * uic_Label8;
lv_obj_t * uic_IdleButton;
lv_obj_t * uic_Label7;
lv_obj_t * uic_RunButton;
lv_obj_t * uic_AngleIndicator;
lv_obj_t * uic_ModeSelectButtonLabel0;
lv_obj_t * uic_ModeSelectButton0;
lv_obj_t * uic_ModeSelectButtonLabel1;
lv_obj_t * uic_ModeSelectButton1;
lv_obj_t * uic_ModeSelectButtonLabel2;
lv_obj_t * uic_ModeSelectButton2;
lv_obj_t * uic_ModeSelect;
lv_obj_t * uic_InterPositonCheckbox;
lv_obj_t * uic_MacaoShootCheckbox;
lv_obj_t * uic_Label4;
lv_obj_t * uic_BackButton0;
lv_obj_t * uic_DropDown0;
lv_obj_t * uic_ActionSelectAppScreen;
lv_obj_t * ui_ActionSelectAppScreen = NULL;
lv_obj_t * ui_DropDown0 = NULL;
lv_obj_t * ui_BackButton0 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_MacaoShootCheckbox = NULL;
lv_obj_t * ui_InterPositonCheckbox = NULL;
lv_obj_t * ui_ModeSelect = NULL;
lv_obj_t * ui_ModeSelectButton2 = NULL;
lv_obj_t * ui_ModeSelectButtonLabel2 = NULL;
lv_obj_t * ui_ModeSelectButton1 = NULL;
lv_obj_t * ui_ModeSelectButtonLabel1 = NULL;
lv_obj_t * ui_ModeSelectButton0 = NULL;
lv_obj_t * ui_ModeSelectButtonLabel0 = NULL;
lv_obj_t * ui_AngleIndicator = NULL;
lv_obj_t * ui_Run = NULL;
lv_obj_t * ui_RunButton = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_IdleButton = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_Panel1 = NULL;
// event funtions
void ui_event_BackButton0(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_HomeScreen, LV_SCR_LOAD_ANIM_FADE_ON, 10, 0, &ui_HomeScreen_screen_init);
    }
}

void ui_event_ModeSelectButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ModeSelectButton0, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_ModeSelectButton2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_ModeSelectButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ModeSelectButton2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_ModeSelectButton1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_ModeSelectButton0(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ModeSelectButton1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_ModeSelectButton0, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_RunButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_IdleButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_RunButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_IdleButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_RunButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_IdleButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

// build funtions

void ui_ActionSelectAppScreen_screen_init(void)
{
    ui_ActionSelectAppScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ActionSelectAppScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DropDown0 = lv_dropdown_create(ui_ActionSelectAppScreen);
    lv_dropdown_set_dir(ui_DropDown0, LV_DIR_TOP);
    lv_dropdown_set_options(ui_DropDown0, "Attacker\nDefender\nRadicon");
    lv_obj_set_width(ui_DropDown0, 248);
    lv_obj_set_height(ui_DropDown0, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_x(ui_DropDown0, 3);
    lv_obj_set_y(ui_DropDown0, 3);
    lv_obj_add_flag(ui_DropDown0, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_BackButton0 = lv_btn_create(ui_ActionSelectAppScreen);
    lv_obj_set_width(ui_BackButton0, 60);
    lv_obj_set_height(ui_BackButton0, 35);
    lv_obj_set_x(ui_BackButton0, 257);
    lv_obj_set_y(ui_BackButton0, 3);
    lv_obj_add_flag(ui_BackButton0, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BackButton0, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BackButton0, lv_color_hex(0xFF4F4F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BackButton0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_BackButton0);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "BACK");

    ui_MacaoShootCheckbox = lv_checkbox_create(ui_ActionSelectAppScreen);
    lv_checkbox_set_text(ui_MacaoShootCheckbox, "MacaoShoot");
    lv_obj_set_width(ui_MacaoShootCheckbox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MacaoShootCheckbox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MacaoShootCheckbox, 3);
    lv_obj_set_y(ui_MacaoShootCheckbox, 180);
    lv_obj_add_state(ui_MacaoShootCheckbox, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_MacaoShootCheckbox, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_InterPositonCheckbox = lv_checkbox_create(ui_ActionSelectAppScreen);
    lv_checkbox_set_text(ui_InterPositonCheckbox, "InterPositon");
    lv_obj_set_width(ui_InterPositonCheckbox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_InterPositonCheckbox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_InterPositonCheckbox, 3);
    lv_obj_set_y(ui_InterPositonCheckbox, 210);
    lv_obj_add_state(ui_InterPositonCheckbox, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_InterPositonCheckbox, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_ModeSelect = lv_obj_create(ui_ActionSelectAppScreen);
    lv_obj_set_width(ui_ModeSelect, 116);
    lv_obj_set_height(ui_ModeSelect, 116);
    lv_obj_set_x(ui_ModeSelect, 194);
    lv_obj_set_y(ui_ModeSelect, 52);
    lv_obj_clear_flag(ui_ModeSelect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ModeSelect, 58, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ModeSelect, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ModeSelect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ModeSelect, lv_color_hex(0xD5D2D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ModeSelect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ModeSelect, 7, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ModeSelectButton2 = lv_btn_create(ui_ModeSelect);
    lv_obj_set_width(ui_ModeSelectButton2, 74);
    lv_obj_set_height(ui_ModeSelectButton2, 74);
    lv_obj_set_align(ui_ModeSelectButton2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ModeSelectButton2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ModeSelectButton2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ModeSelectButton2, lv_color_hex(0xD5D2D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ModeSelectButton2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ModeSelectButton2, 0, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_color(ui_ModeSelectButton2, lv_color_hex(0xD3D904), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_opa(ui_ModeSelectButton2, 255, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_radius(ui_ModeSelectButton2, 0, LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_bg_color(ui_ModeSelectButton2, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_bg_opa(ui_ModeSelectButton2, 255, LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_radius(ui_ModeSelectButton2, 0, LV_PART_MAIN | LV_STATE_USER_3);
    lv_obj_set_style_bg_color(ui_ModeSelectButton2, lv_color_hex(0x545454), LV_PART_MAIN | LV_STATE_USER_3);
    lv_obj_set_style_bg_opa(ui_ModeSelectButton2, 255, LV_PART_MAIN | LV_STATE_USER_3);

    ui_ModeSelectButtonLabel2 = lv_label_create(ui_ModeSelectButton2);
    lv_obj_set_width(ui_ModeSelectButtonLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ModeSelectButtonLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ModeSelectButtonLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ModeSelectButtonLabel2, "GYRO");

    ui_ModeSelectButton1 = lv_btn_create(ui_ModeSelect);
    lv_obj_set_width(ui_ModeSelectButton1, 74);
    lv_obj_set_height(ui_ModeSelectButton1, 74);
    lv_obj_set_align(ui_ModeSelectButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ModeSelectButton1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ModeSelectButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ModeSelectButton1, lv_color_hex(0xE7DF29), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ModeSelectButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ModeSelectButton1, 0, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_color(ui_ModeSelectButton1, lv_color_hex(0xD3D904), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_opa(ui_ModeSelectButton1, 255, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_radius(ui_ModeSelectButton1, 0, LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_bg_color(ui_ModeSelectButton1, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_bg_opa(ui_ModeSelectButton1, 255, LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_radius(ui_ModeSelectButton1, 0, LV_PART_MAIN | LV_STATE_USER_3);
    lv_obj_set_style_bg_color(ui_ModeSelectButton1, lv_color_hex(0x545454), LV_PART_MAIN | LV_STATE_USER_3);
    lv_obj_set_style_bg_opa(ui_ModeSelectButton1, 255, LV_PART_MAIN | LV_STATE_USER_3);

    ui_ModeSelectButtonLabel1 = lv_label_create(ui_ModeSelectButton1);
    lv_obj_set_width(ui_ModeSelectButtonLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ModeSelectButtonLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ModeSelectButtonLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ModeSelectButtonLabel1, "YELLOW\nGOAL");

    ui_ModeSelectButton0 = lv_btn_create(ui_ModeSelect);
    lv_obj_set_width(ui_ModeSelectButton0, 74);
    lv_obj_set_height(ui_ModeSelectButton0, 74);
    lv_obj_set_align(ui_ModeSelectButton0, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ModeSelectButton0, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ModeSelectButton0, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ModeSelectButton0, 0, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_color(ui_ModeSelectButton0, lv_color_hex(0xD3D904), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_opa(ui_ModeSelectButton0, 255, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_radius(ui_ModeSelectButton0, 0, LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_bg_color(ui_ModeSelectButton0, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_bg_opa(ui_ModeSelectButton0, 255, LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_radius(ui_ModeSelectButton0, 0, LV_PART_MAIN | LV_STATE_USER_3);
    lv_obj_set_style_bg_color(ui_ModeSelectButton0, lv_color_hex(0x545454), LV_PART_MAIN | LV_STATE_USER_3);
    lv_obj_set_style_bg_opa(ui_ModeSelectButton0, 255, LV_PART_MAIN | LV_STATE_USER_3);

    ui_ModeSelectButtonLabel0 = lv_label_create(ui_ModeSelectButton0);
    lv_obj_set_width(ui_ModeSelectButtonLabel0, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ModeSelectButtonLabel0, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ModeSelectButtonLabel0, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ModeSelectButtonLabel0, "BLUE\nGOAL");

    ui_AngleIndicator = lv_obj_create(ui_ActionSelectAppScreen);
    lv_obj_set_width(ui_AngleIndicator, 16);
    lv_obj_set_height(ui_AngleIndicator, 16);
    lv_obj_set_x(ui_AngleIndicator, 244);
    lv_obj_set_y(ui_AngleIndicator, 48);
    lv_obj_clear_flag(ui_AngleIndicator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_AngleIndicator, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AngleIndicator, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AngleIndicator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_AngleIndicator, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_AngleIndicator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_AngleIndicator, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Run = lv_obj_create(ui_ActionSelectAppScreen);
    lv_obj_set_width(ui_Run, 186);
    lv_obj_set_height(ui_Run, 126);
    lv_obj_set_x(ui_Run, 0);
    lv_obj_set_y(ui_Run, 47);
    lv_obj_clear_flag(ui_Run, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Run, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Run, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Run, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Run, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RunButton = lv_btn_create(ui_Run);
    lv_obj_set_width(ui_RunButton, 180);
    lv_obj_set_height(ui_RunButton, 120);
    lv_obj_set_align(ui_RunButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RunButton, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_RunButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_RunButton, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RunButton, lv_color_hex(0x2DA041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RunButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_RunButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_RunButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_RunButton, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_RunButton, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_RunButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_RunButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RunButton, lv_color_hex(0x414141), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_opa(ui_RunButton, 255, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_color(ui_RunButton, lv_color_hex(0x2DA041), LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_bg_opa(ui_RunButton, 255, LV_PART_MAIN | LV_STATE_USER_2);

    ui_Label7 = lv_label_create(ui_RunButton);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "RUN");

    ui_IdleButton = lv_btn_create(ui_Run);
    lv_obj_set_width(ui_IdleButton, 180);
    lv_obj_set_height(ui_IdleButton, 120);
    lv_obj_set_align(ui_IdleButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IdleButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_IdleButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_IdleButton, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_IdleButton, lv_color_hex(0x414141), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IdleButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_IdleButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_IdleButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_IdleButton, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_IdleButton, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_IdleButton, lv_color_hex(0x414141), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_opa(ui_IdleButton, 255, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_color(ui_IdleButton, lv_color_hex(0x2DA041), LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_bg_opa(ui_IdleButton, 255, LV_PART_MAIN | LV_STATE_USER_2);

    ui_Label8 = lv_label_create(ui_IdleButton);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "IDLE");

    ui_Panel1 = lv_obj_create(ui_ActionSelectAppScreen);
    lv_obj_set_width(ui_Panel1, 170);
    lv_obj_set_height(ui_Panel1, 50);
    lv_obj_set_x(ui_Panel1, 140);
    lv_obj_set_y(ui_Panel1, 180);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_BackButton0, ui_event_BackButton0, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ModeSelectButton2, ui_event_ModeSelectButton2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ModeSelectButton1, ui_event_ModeSelectButton1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ModeSelectButton0, ui_event_ModeSelectButton0, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RunButton, ui_event_RunButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_IdleButton, ui_event_IdleButton, LV_EVENT_ALL, NULL);
    uic_ActionSelectAppScreen = ui_ActionSelectAppScreen;
    uic_DropDown0 = ui_DropDown0;
    uic_BackButton0 = ui_BackButton0;
    uic_Label4 = ui_Label4;
    uic_MacaoShootCheckbox = ui_MacaoShootCheckbox;
    uic_InterPositonCheckbox = ui_InterPositonCheckbox;
    uic_ModeSelect = ui_ModeSelect;
    uic_ModeSelectButton2 = ui_ModeSelectButton2;
    uic_ModeSelectButtonLabel2 = ui_ModeSelectButtonLabel2;
    uic_ModeSelectButton1 = ui_ModeSelectButton1;
    uic_ModeSelectButtonLabel1 = ui_ModeSelectButtonLabel1;
    uic_ModeSelectButton0 = ui_ModeSelectButton0;
    uic_ModeSelectButtonLabel0 = ui_ModeSelectButtonLabel0;
    uic_AngleIndicator = ui_AngleIndicator;
    uic_RunButton = ui_RunButton;
    uic_Label7 = ui_Label7;
    uic_IdleButton = ui_IdleButton;
    uic_Label8 = ui_Label8;

}

void ui_ActionSelectAppScreen_screen_destroy(void)
{
    if(ui_ActionSelectAppScreen) lv_obj_del(ui_ActionSelectAppScreen);

    // NULL screen variables
    uic_ActionSelectAppScreen = NULL;
    ui_ActionSelectAppScreen = NULL;
    uic_DropDown0 = NULL;
    ui_DropDown0 = NULL;
    uic_BackButton0 = NULL;
    ui_BackButton0 = NULL;
    uic_Label4 = NULL;
    ui_Label4 = NULL;
    uic_MacaoShootCheckbox = NULL;
    ui_MacaoShootCheckbox = NULL;
    uic_InterPositonCheckbox = NULL;
    ui_InterPositonCheckbox = NULL;
    uic_ModeSelect = NULL;
    ui_ModeSelect = NULL;
    uic_ModeSelectButton2 = NULL;
    ui_ModeSelectButton2 = NULL;
    uic_ModeSelectButtonLabel2 = NULL;
    ui_ModeSelectButtonLabel2 = NULL;
    uic_ModeSelectButton1 = NULL;
    ui_ModeSelectButton1 = NULL;
    uic_ModeSelectButtonLabel1 = NULL;
    ui_ModeSelectButtonLabel1 = NULL;
    uic_ModeSelectButton0 = NULL;
    ui_ModeSelectButton0 = NULL;
    uic_ModeSelectButtonLabel0 = NULL;
    ui_ModeSelectButtonLabel0 = NULL;
    uic_AngleIndicator = NULL;
    ui_AngleIndicator = NULL;
    ui_Run = NULL;
    uic_RunButton = NULL;
    ui_RunButton = NULL;
    uic_Label7 = NULL;
    ui_Label7 = NULL;
    uic_IdleButton = NULL;
    ui_IdleButton = NULL;
    uic_Label8 = NULL;
    ui_Label8 = NULL;
    ui_Panel1 = NULL;

}
