// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_ACTION_H
#define UI_ACTION_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Action
extern void ui_Action_screen_init(void);
extern void ui_Action_screen_destroy(void);
extern void ui_event_Action(lv_event_t * e);
extern lv_obj_t * ui_Action;
extern lv_obj_t * ui_ActionTopContainer;
extern void ui_event_ActionDropdown(lv_event_t * e);
extern lv_obj_t * ui_ActionDropdown;
extern void ui_event_ActionBackButton(lv_event_t * e);
extern lv_obj_t * ui_ActionBackButton;
extern lv_obj_t * ui_ActionBackLabel;
extern lv_obj_t * ui_ActionMidContainer;
extern lv_obj_t * ui_ActionLeverContainer;
extern void ui_event_ActionLeverRunButton(lv_event_t * e);
extern lv_obj_t * ui_ActionLeverRunButton;
extern lv_obj_t * ui_ActionLeverRunLabel;
extern void ui_event_ActionLeverIdleButton(lv_event_t * e);
extern lv_obj_t * ui_ActionLeverIdleButton;
extern lv_obj_t * ui_ActionLeverIdleLabel;
extern lv_obj_t * ui_ActionMeterContainer;
extern lv_obj_t * ui_ActionMeterPanel;
extern void ui_event_ActionMeterButton(lv_event_t * e);
extern lv_obj_t * ui_ActionMeterButton;
extern lv_obj_t * ui_ActionMeterPointorPanel;
extern lv_obj_t * ui_ActionConfigContainer;
extern lv_obj_t * ui_ActionConfigCheckbox1;
extern lv_obj_t * ui_ActionConfigCheckbox2;
extern lv_obj_t * ui_ActionConfigCheckbox3;
extern lv_obj_t * ui_ActionConfigCheckbox4;
extern lv_obj_t * ui_ActionDebugPanel;
extern lv_obj_t * ui_ActionDebugLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

