// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: test

#ifndef UI_ACTIONSELECTAPPSCREEN_H
#define UI_ACTIONSELECTAPPSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ActionSelectAppScreen
extern void ui_ActionSelectAppScreen_screen_init(void);
extern void ui_ActionSelectAppScreen_screen_destroy(void);
extern lv_obj_t * ui_ActionSelectAppScreen;
extern void ui_event_DropDown0(lv_event_t * e);
extern lv_obj_t * ui_DropDown0;
extern void ui_event_BackButton0(lv_event_t * e);
extern lv_obj_t * ui_BackButton0;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_MacaoShootCheckbox;
extern lv_obj_t * ui_InterPositonCheckbox;
extern lv_obj_t * ui_DirectionSelect0;
extern void ui_event_DirectionSelectButton2(lv_event_t * e);
extern lv_obj_t * ui_DirectionSelectButton2;
extern lv_obj_t * ui_DirectionSelectButtonLabel2;
extern void ui_event_DirectionSelectButton1(lv_event_t * e);
extern lv_obj_t * ui_DirectionSelectButton1;
extern lv_obj_t * ui_DirectionSelectButtonLabel1;
extern void ui_event_DirectionSelectButton0(lv_event_t * e);
extern lv_obj_t * ui_DirectionSelectButton0;
extern lv_obj_t * ui_DirectionSelectButtonLabel0;
extern lv_obj_t * ui_DirectionSelect1;
extern void ui_event_DirectionSelectButton3(lv_event_t * e);
extern lv_obj_t * ui_DirectionSelectButton3;
extern lv_obj_t * ui_DirectionSelectButtonLabel3;
extern void ui_event_DirectionSelectButton4(lv_event_t * e);
extern lv_obj_t * ui_DirectionSelectButton4;
extern lv_obj_t * ui_DirectionSelectButtonLabel4;
extern lv_obj_t * ui_AngleIndicator;
extern lv_obj_t * ui_Run;
extern void ui_event_RunButton(lv_event_t * e);
extern lv_obj_t * ui_RunButton;
extern lv_obj_t * ui_Label7;
extern void ui_event_IdleButton(lv_event_t * e);
extern lv_obj_t * ui_IdleButton;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_FreePanel;
// CUSTOM VARIABLES
extern lv_obj_t * uic_ActionSelectAppScreen;
extern lv_obj_t * uic_DropDown0;
extern lv_obj_t * uic_BackButton0;
extern lv_obj_t * uic_Label4;
extern lv_obj_t * uic_MacaoShootCheckbox;
extern lv_obj_t * uic_InterPositonCheckbox;
extern lv_obj_t * uic_DirectionSelect0;
extern lv_obj_t * uic_DirectionSelectButton2;
extern lv_obj_t * uic_DirectionSelectButtonLabel2;
extern lv_obj_t * uic_DirectionSelectButton1;
extern lv_obj_t * uic_DirectionSelectButtonLabel1;
extern lv_obj_t * uic_DirectionSelectButton0;
extern lv_obj_t * uic_DirectionSelectButtonLabel0;
extern lv_obj_t * uic_DirectionSelect1;
extern lv_obj_t * uic_DirectionSelectButton3;
extern lv_obj_t * uic_DirectionSelectButtonLabel3;
extern lv_obj_t * uic_DirectionSelectButton4;
extern lv_obj_t * uic_DirectionSelectButtonLabel4;
extern lv_obj_t * uic_AngleIndicator;
extern lv_obj_t * uic_Run;
extern lv_obj_t * uic_RunButton;
extern lv_obj_t * uic_Label7;
extern lv_obj_t * uic_IdleButton;
extern lv_obj_t * uic_Label8;
extern lv_obj_t * uic_FreePanel;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

