// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_COMMUNICATION_H
#define UI_COMMUNICATION_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Communication
extern void ui_Communication_screen_init(void);
extern void ui_Communication_screen_destroy(void);
extern lv_obj_t * ui_Communication;
extern lv_obj_t * ui_CommunicationTopContainer;
extern lv_obj_t * ui_CommunicationDropdown;
extern void ui_event_CommunicationBackButton(lv_event_t * e);
extern lv_obj_t * ui_CommunicationBackButton;
extern lv_obj_t * ui_CommunicationBackLabel;
extern lv_obj_t * ui_CommunicationMidContainer;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

