// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Communication = NULL;
lv_obj_t * ui_CommunicationTopContainer = NULL;
lv_obj_t * ui_CommunicationDropdown = NULL;
lv_obj_t * ui_CommunicationBackButton = NULL;
lv_obj_t * ui_CommunicationBackLabel = NULL;
lv_obj_t * ui_CommunicationMidContainer = NULL;
// event funtions
void ui_event_Communication(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        communication_loaded_event(e);
    }
}

void ui_event_CommunicationBackButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_HomeScreen, LV_SCR_LOAD_ANIM_FADE_ON, 10, 0, &ui_HomeScreen_screen_init);
    }
}

// build funtions

void ui_Communication_screen_init(void)
{
    ui_Communication = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Communication, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CommunicationTopContainer = lv_obj_create(ui_Communication);
    lv_obj_remove_style_all(ui_CommunicationTopContainer);
    lv_obj_set_width(ui_CommunicationTopContainer, 320);
    lv_obj_set_height(ui_CommunicationTopContainer, 40);
    lv_obj_clear_flag(ui_CommunicationTopContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CommunicationDropdown = lv_dropdown_create(ui_CommunicationTopContainer);
    lv_dropdown_set_options(ui_CommunicationDropdown, "Transmit\nReceive");
    lv_obj_set_width(ui_CommunicationDropdown, 258);
    lv_obj_set_height(ui_CommunicationDropdown, 38);
    lv_obj_set_x(ui_CommunicationDropdown, 1);
    lv_obj_set_y(ui_CommunicationDropdown, 1);
    lv_obj_add_flag(ui_CommunicationDropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_CommunicationBackButton = lv_btn_create(ui_CommunicationTopContainer);
    lv_obj_set_width(ui_CommunicationBackButton, 58);
    lv_obj_set_height(ui_CommunicationBackButton, 38);
    lv_obj_set_x(ui_CommunicationBackButton, 261);
    lv_obj_set_y(ui_CommunicationBackButton, 1);
    lv_obj_add_flag(ui_CommunicationBackButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_CommunicationBackButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CommunicationBackButton, lv_color_hex(0xFF3333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CommunicationBackButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_CommunicationBackButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_CommunicationBackButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_CommunicationBackButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_CommunicationBackButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CommunicationBackLabel = lv_label_create(ui_CommunicationBackButton);
    lv_obj_set_width(ui_CommunicationBackLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CommunicationBackLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CommunicationBackLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CommunicationBackLabel, "Back");
    lv_obj_set_style_text_color(ui_CommunicationBackLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CommunicationBackLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_CommunicationBackLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_CommunicationBackLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_CommunicationBackLabel, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_CommunicationBackLabel, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CommunicationBackLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CommunicationMidContainer = lv_obj_create(ui_Communication);
    lv_obj_remove_style_all(ui_CommunicationMidContainer);
    lv_obj_set_width(ui_CommunicationMidContainer, 320);
    lv_obj_set_height(ui_CommunicationMidContainer, 200);
    lv_obj_set_x(ui_CommunicationMidContainer, 0);
    lv_obj_set_y(ui_CommunicationMidContainer, 40);
    lv_obj_clear_flag(ui_CommunicationMidContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_CommunicationBackButton, ui_event_CommunicationBackButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Communication, ui_event_Communication, LV_EVENT_ALL, NULL);

}

void ui_Communication_screen_destroy(void)
{
    if(ui_Communication) lv_obj_del(ui_Communication);

    // NULL screen variables
    ui_Communication = NULL;
    ui_CommunicationTopContainer = NULL;
    ui_CommunicationDropdown = NULL;
    ui_CommunicationBackButton = NULL;
    ui_CommunicationBackLabel = NULL;
    ui_CommunicationMidContainer = NULL;

}
