// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: test

#include "ui.h"

void MessageAppDropDownFunc(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if (code == LV_EVENT_VALUE_CHANGED)
    {
        lv_obj_t *obj = lv_event_get_target(e);

        char buf[32]; 
        lv_dropdown_get_selected_str(obj, buf, sizeof(buf));

        if(strcmp(buf, "Send") == 0)
        {
            // Sendを表示、Receiveを隠す
            lv_obj_clear_flag(uic_Send, LV_OBJ_FLAG_HIDDEN);
            lv_obj_add_flag(uic_Receive, LV_OBJ_FLAG_HIDDEN);
        }
        else // if(strcmp(buf, "Receive") == 0)
        {
            // Sendを隠し、Receiveを表示
            lv_obj_add_flag(uic_Send, LV_OBJ_FLAG_HIDDEN);
            lv_obj_clear_flag(uic_Receive, LV_OBJ_FLAG_HIDDEN);
        }
    }
}

void ActionSelectAppDropDownFunc(lv_event_t * e)
{
	lv_event_code_t code = lv_event_get_code(e);
    if (code == LV_EVENT_VALUE_CHANGED)
    {
        lv_obj_t *obj = lv_event_get_target(e);

        char buf[32]; 
        lv_dropdown_get_selected_str(obj, buf, sizeof(buf));
    }
}

void TestAppDropDownFunc(lv_event_t * e)
{
	lv_event_code_t code = lv_event_get_code(e);
    if (code == LV_EVENT_VALUE_CHANGED)
    {
        lv_obj_t *obj = lv_event_get_target(e);

        char buf[32]; 
        lv_dropdown_get_selected_str(obj, buf, sizeof(buf));
    }
}

void SensorCheckAppDropDownFunc(lv_event_t * e)
{
	lv_event_code_t code = lv_event_get_code(e);
    if (code == LV_EVENT_VALUE_CHANGED)
    {
        lv_obj_t *obj = lv_event_get_target(e);

        char buf[32]; 
        lv_dropdown_get_selected_str(obj, buf, sizeof(buf));
    }
}
