// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

UI_STATE ui_state = HOME; // Current UI state

// Action

void action_loaded_event(lv_event_t *e)
{
	uint16_t selected_index = lv_dropdown_get_selected(ui_ActionDropdown);
	switch (selected_index)
	{
	case 0: // Offense
		ui_state = ACTION_OFFENSE;
		break;
	case 1: // Defense
		ui_state = ACTION_DEFENSE;
		break;
	case 2: // RadioControl
		ui_state = ACTION_RADIOCONTROL;
		break;
	}
}

int action_meter_type = 0;

void action_dropdown_value_changed_event(lv_event_t *e)
{
	uint16_t selected_index = lv_dropdown_get_selected(ui_ActionDropdown);

	switch (selected_index)
	{
	case 0: // Offense
		ui_state = ACTION_OFFENSE;
		break;
	case 1: // Defense
		ui_state = ACTION_DEFENSE;
		break;
	case 2: // RadioControl
		ui_state = ACTION_RADIOCONTROL;
		break;
	}

	action_meter_type = 0;
	lv_obj_add_state(ui_ActionMeterButton, LV_STATE_USER_1);
	lv_obj_clear_state(ui_ActionMeterButton, LV_STATE_USER_2);
	lv_obj_clear_state(ui_ActionMeterButton, LV_STATE_USER_3);

	lv_obj_add_flag(ui_ActionLeverRunButton, LV_OBJ_FLAG_HIDDEN);
	lv_obj_clear_flag(ui_ActionLeverIdleButton, LV_OBJ_FLAG_HIDDEN);
}

void action_meter_switch_event(lv_event_t *e)
{
	uint16_t selected_index = lv_dropdown_get_selected(ui_ActionDropdown);

	switch (selected_index)
	{
	case 0: // Offense
		action_meter_type = (action_meter_type + 1) % 3;
		break;
	case 1: // Defense
		action_meter_type = (action_meter_type + 1) % 2;
		break;
	case 2: // RadioControl
		action_meter_type = (action_meter_type + 1) % 3;
		break;
	}

	switch (action_meter_type)
	{
	case 0:
		lv_obj_add_state(ui_ActionMeterButton, LV_STATE_USER_1);
		lv_obj_clear_state(ui_ActionMeterButton, LV_STATE_USER_2);
		lv_obj_clear_state(ui_ActionMeterButton, LV_STATE_USER_3);
		break;
	case 1:
		lv_obj_add_state(ui_ActionMeterButton, LV_STATE_USER_2);
		lv_obj_clear_state(ui_ActionMeterButton, LV_STATE_USER_1);
		lv_obj_clear_state(ui_ActionMeterButton, LV_STATE_USER_3);
		break;
	case 2:
		lv_obj_add_state(ui_ActionMeterButton, LV_STATE_USER_3);
		lv_obj_clear_state(ui_ActionMeterButton, LV_STATE_USER_1);
		lv_obj_clear_state(ui_ActionMeterButton, LV_STATE_USER_2);
		break;
	}
}

// Test

void test_loaded_event(lv_event_t *e)
{
	uint16_t selected_index = lv_dropdown_get_selected(ui_TestDropdown);
	switch (selected_index)
	{
	case 0: // Kicker
		ui_state = TEST_KICKER;
		break;
	case 1: // Dribbler
		ui_state = TEST_DRIBBLER;
		break;
	case 2: // Motor
		ui_state = TEST_MOTOR;
		break;
	}
}

void test_dropdown_value_changed_event(lv_event_t *e)
{
	uint16_t selected_index = lv_dropdown_get_selected(ui_TestDropdown);

	switch (selected_index)
	{
	case 0: // Kicker
		ui_state = TEST_KICKER;
		lv_obj_clear_flag(ui_TestKickerContainer, LV_OBJ_FLAG_HIDDEN);
		lv_obj_add_flag(ui_TestDribblerContainer, LV_OBJ_FLAG_HIDDEN);
		lv_obj_add_flag(ui_TestMotorContainer, LV_OBJ_FLAG_HIDDEN);
		break;
	case 1: // Dribbler
		ui_state = TEST_DRIBBLER;
		lv_obj_clear_flag(ui_TestDribblerContainer, LV_OBJ_FLAG_HIDDEN);
		lv_obj_add_flag(ui_TestKickerContainer, LV_OBJ_FLAG_HIDDEN);
		lv_obj_add_flag(ui_TestMotorContainer, LV_OBJ_FLAG_HIDDEN);

		lv_obj_add_flag(ui_TestDribblerLeverRunButton, LV_OBJ_FLAG_HIDDEN);
		lv_obj_clear_flag(ui_TestDribblerLeverIdleButton, LV_OBJ_FLAG_HIDDEN);
		break;
	case 2: // Motor
		ui_state = TEST_MOTOR;
		lv_obj_clear_flag(ui_TestMotorContainer, LV_OBJ_FLAG_HIDDEN);
		lv_obj_add_flag(ui_TestKickerContainer, LV_OBJ_FLAG_HIDDEN);
		lv_obj_add_flag(ui_TestDribblerContainer, LV_OBJ_FLAG_HIDDEN);

		lv_obj_add_flag(ui_TestMotorLeverRunButton, LV_OBJ_FLAG_HIDDEN);
		lv_obj_clear_flag(ui_TestMotorLeverIdleButton, LV_OBJ_FLAG_HIDDEN);
		break;
	}
}

int testmotor_meter_type = 0;

void testmotor_meter_switch_event(lv_event_t *e)
{
	testmotor_meter_type = (testmotor_meter_type + 1) % 3;

	switch (testmotor_meter_type)
	{
	case 0:
		lv_obj_add_state(ui_TestMotorMeterButton, LV_STATE_USER_1);
		lv_obj_clear_state(ui_TestMotorMeterButton, LV_STATE_USER_2);
		lv_obj_clear_state(ui_TestMotorMeterButton, LV_STATE_USER_3);
		break;
	case 1:
		lv_obj_add_state(ui_TestMotorMeterButton, LV_STATE_USER_2);
		lv_obj_clear_state(ui_TestMotorMeterButton, LV_STATE_USER_1);
		lv_obj_clear_state(ui_TestMotorMeterButton, LV_STATE_USER_3);
		break;
	case 2:
		lv_obj_add_state(ui_TestMotorMeterButton, LV_STATE_USER_3);
		lv_obj_clear_state(ui_TestMotorMeterButton, LV_STATE_USER_1);
		lv_obj_clear_state(ui_TestMotorMeterButton, LV_STATE_USER_2);
		break;
	}
}

// SensorMonitor

void sensormonitor_loaded_event(lv_event_t *e)
{
	uint16_t selected_index = lv_dropdown_get_selected(ui_SensorMonitorDropdown);

	switch (selected_index)
	{
	case 0: // Ball
		ui_state = SENSORMONITOR_BALL;
		break;
	case 1: // Line
		ui_state = SENSORMONITOR_LINE;
		break;
	case 2: // Gyro
		ui_state = SENSORMONITOR_GYRO;
		break;
	case 3: // Goal
		ui_state = SENSORMONITOR_GOAL;
		break;
	case 4: // Lidar
		ui_state = SENSORMONITOR_LIDAR;
		break;
	}
}

void sensormonitor_dropdown_value_changed_event(lv_event_t *e)
{
	uint16_t selected_index = lv_dropdown_get_selected(ui_SensorMonitorDropdown);

	switch (selected_index)
	{
	case 0: // Ball
		ui_state = SENSORMONITOR_BALL;
		lv_obj_clear_flag(ui_SensorMonitorBallContainer, LV_OBJ_FLAG_HIDDEN);
		lv_obj_add_flag(ui_SensorMonitorLineContainer, LV_OBJ_FLAG_HIDDEN);
		lv_obj_add_flag(ui_SensorMonitorGyroContainer, LV_OBJ_FLAG_HIDDEN);
		lv_obj_add_flag(ui_SensorMonitorGoalContainer, LV_OBJ_FLAG_HIDDEN);
		lv_obj_add_flag(ui_SensorMonitorLidarContainer, LV_OBJ_FLAG_HIDDEN);
		break;
	case 1: // Line
		ui_state = SENSORMONITOR_LINE;
		lv_obj_clear_flag(ui_SensorMonitorLineContainer, LV_OBJ_FLAG_HIDDEN);
		lv_obj_add_flag(ui_SensorMonitorBallContainer, LV_OBJ_FLAG_HIDDEN);
		lv_obj_add_flag(ui_SensorMonitorGyroContainer, LV_OBJ_FLAG_HIDDEN);
		lv_obj_add_flag(ui_SensorMonitorGoalContainer, LV_OBJ_FLAG_HIDDEN);
		lv_obj_add_flag(ui_SensorMonitorLidarContainer, LV_OBJ_FLAG_HIDDEN);
		break;
	case 2: // Gyro
		ui_state = SENSORMONITOR_GYRO;
		lv_obj_clear_flag(ui_SensorMonitorGyroContainer, LV_OBJ_FLAG_HIDDEN);
		lv_obj_add_flag(ui_SensorMonitorBallContainer, LV_OBJ_FLAG_HIDDEN);
		lv_obj_add_flag(ui_SensorMonitorLineContainer, LV_OBJ_FLAG_HIDDEN);
		lv_obj_add_flag(ui_SensorMonitorGoalContainer, LV_OBJ_FLAG_HIDDEN);
		lv_obj_add_flag(ui_SensorMonitorLidarContainer, LV_OBJ_FLAG_HIDDEN);
		break;
	case 3: // Goal
		ui_state = SENSORMONITOR_GOAL;
		lv_obj_clear_flag(ui_SensorMonitorGoalContainer, LV_OBJ_FLAG_HIDDEN);
		lv_obj_add_flag(ui_SensorMonitorBallContainer, LV_OBJ_FLAG_HIDDEN);
		lv_obj_add_flag(ui_SensorMonitorLineContainer, LV_OBJ_FLAG_HIDDEN);
		lv_obj_add_flag(ui_SensorMonitorGyroContainer, LV_OBJ_FLAG_HIDDEN);
		lv_obj_add_flag(ui_SensorMonitorLidarContainer, LV_OBJ_FLAG_HIDDEN);
		break;
	case 4: // Lidar
		ui_state = SENSORMONITOR_LIDAR;
		lv_obj_clear_flag(ui_SensorMonitorLidarContainer, LV_OBJ_FLAG_HIDDEN);
		lv_obj_add_flag(ui_SensorMonitorBallContainer, LV_OBJ_FLAG_HIDDEN);
		lv_obj_add_flag(ui_SensorMonitorLineContainer, LV_OBJ_FLAG_HIDDEN);
		lv_obj_add_flag(ui_SensorMonitorGyroContainer, LV_OBJ_FLAG_HIDDEN);
		lv_obj_add_flag(ui_SensorMonitorGoalContainer, LV_OBJ_FLAG_HIDDEN);
		break;
	}
}

// Communication

void communication_loaded_event(lv_event_t *e)
{
	uint16_t selected_index = lv_dropdown_get_selected(ui_CommunicationDropdown);

	switch (selected_index)
	{
	case 0: // Transmit
		ui_state = COMMUNICATION_TRANSMIT;
		break;
	case 1: // Receive
		ui_state = COMMUNICATION_RECEIVE;
		break;
	}
}

// Home

void home_loaded_event(lv_event_t *e)
{
	ui_state = HOME;

	// Action
	lv_dropdown_set_selected(ui_ActionDropdown, 0);

	action_meter_type = 0;
	lv_obj_add_state(ui_ActionMeterButton, LV_STATE_USER_1);
	lv_obj_clear_state(ui_ActionMeterButton, LV_STATE_USER_2);
	lv_obj_clear_state(ui_ActionMeterButton, LV_STATE_USER_3);

	lv_obj_add_flag(ui_ActionLeverRunButton, LV_OBJ_FLAG_HIDDEN);
	lv_obj_clear_flag(ui_ActionLeverIdleButton, LV_OBJ_FLAG_HIDDEN);

	// Test
	lv_dropdown_set_selected(ui_TestDropdown, 0);

	lv_obj_clear_flag(ui_TestKickerContainer, LV_OBJ_FLAG_HIDDEN);
	lv_obj_add_flag(ui_TestDribblerContainer, LV_OBJ_FLAG_HIDDEN);
	lv_obj_add_flag(ui_TestMotorContainer, LV_OBJ_FLAG_HIDDEN);

	lv_obj_add_flag(ui_TestDribblerLeverRunButton, LV_OBJ_FLAG_HIDDEN);
	lv_obj_clear_flag(ui_TestDribblerLeverIdleButton, LV_OBJ_FLAG_HIDDEN);

	lv_obj_add_flag(ui_TestMotorLeverRunButton, LV_OBJ_FLAG_HIDDEN);
	lv_obj_clear_flag(ui_TestMotorLeverIdleButton, LV_OBJ_FLAG_HIDDEN);

	testmotor_meter_type = 0;
	lv_obj_add_state(ui_TestMotorMeterButton, LV_STATE_USER_1);
	lv_obj_clear_state(ui_TestMotorMeterButton, LV_STATE_USER_2);
	lv_obj_clear_state(ui_TestMotorMeterButton, LV_STATE_USER_3);

	// SensorMonitor
	lv_dropdown_set_selected(ui_SensorMonitorDropdown, 0);

	lv_obj_clear_flag(ui_SensorMonitorBallContainer, LV_OBJ_FLAG_HIDDEN);
	lv_obj_add_flag(ui_SensorMonitorLineContainer, LV_OBJ_FLAG_HIDDEN);
	lv_obj_add_flag(ui_SensorMonitorGyroContainer, LV_OBJ_FLAG_HIDDEN);
	lv_obj_add_flag(ui_SensorMonitorGoalContainer, LV_OBJ_FLAG_HIDDEN);
	lv_obj_add_flag(ui_SensorMonitorLidarContainer, LV_OBJ_FLAG_HIDDEN);
}