// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endifs

void home_loaded_event(lv_event_t * e);
void action_loaded_event(lv_event_t * e);
void action_dropdown_value_changed_event(lv_event_t * e);
void action_meter_switch_event(lv_event_t * e);
void test_loaded_event(lv_event_t * e);
void test_dropdown_value_changed_event(lv_event_t * e);
void testmotor_meter_switch_event(lv_event_t * e);
void sensormonitor_loaded_event(lv_event_t * e);
void sensormonitor_dropdown_value_changed_event(lv_event_t * e);
void communication_loaded_event(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
