// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_HOMESCREEN_H
#define UI_HOMESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_HomeScreen
extern void ui_HomeScreen_screen_init(void);
extern void ui_HomeScreen_screen_destroy(void);
extern void ui_event_HomeScreen(lv_event_t * e);
extern lv_obj_t * ui_HomeScreen;
extern void ui_event_ActionOpenButton(lv_event_t * e);
extern lv_obj_t * ui_ActionOpenButton;
extern lv_obj_t * ui_ActionOpenLabel;
extern void ui_event_TestOpenButton(lv_event_t * e);
extern lv_obj_t * ui_TestOpenButton;
extern lv_obj_t * ui_TestOpenLabel;
extern void ui_event_SensorMonitorOpenButton(lv_event_t * e);
extern lv_obj_t * ui_SensorMonitorOpenButton;
extern lv_obj_t * ui_SensorMonitorOpenLabel;
extern void ui_event_CommunicationOpenButton(lv_event_t * e);
extern lv_obj_t * ui_CommunicationOpenButton;
extern lv_obj_t * ui_CommunicationOpenLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

