// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_HomeScreen = NULL;
lv_obj_t * ui_ActionOpenButton = NULL;
lv_obj_t * ui_ActionOpenLabel = NULL;
lv_obj_t * ui_TestOpenButton = NULL;
lv_obj_t * ui_TestOpenLabel = NULL;
lv_obj_t * ui_SensorMonitorOpenButton = NULL;
lv_obj_t * ui_SensorMonitorOpenLabel = NULL;
lv_obj_t * ui_CommunicationOpenButton = NULL;
lv_obj_t * ui_CommunicationOpenLabel = NULL;
// event funtions
void ui_event_HomeScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        home_loaded_event(e);
    }
}

void ui_event_ActionOpenButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Action, LV_SCR_LOAD_ANIM_FADE_ON, 10, 0, &ui_Action_screen_init);
    }
}

void ui_event_TestOpenButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Test, LV_SCR_LOAD_ANIM_FADE_ON, 10, 0, &ui_Test_screen_init);
    }
}

void ui_event_SensorMonitorOpenButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SensorMonitor, LV_SCR_LOAD_ANIM_FADE_ON, 10, 0, &ui_SensorMonitor_screen_init);
    }
}

void ui_event_CommunicationOpenButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Communication, LV_SCR_LOAD_ANIM_FADE_ON, 10, 0, &ui_Communication_screen_init);
    }
}

// build funtions

void ui_HomeScreen_screen_init(void)
{
    ui_HomeScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_HomeScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ActionOpenButton = lv_btn_create(ui_HomeScreen);
    lv_obj_set_width(ui_ActionOpenButton, 160);
    lv_obj_set_height(ui_ActionOpenButton, 120);
    lv_obj_add_flag(ui_ActionOpenButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ActionOpenButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ActionOpenButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ActionOpenButton, lv_color_hex(0xDC2444), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ActionOpenButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ActionOpenLabel = lv_label_create(ui_ActionOpenButton);
    lv_obj_set_width(ui_ActionOpenLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ActionOpenLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ActionOpenLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ActionOpenLabel, "Action");

    ui_TestOpenButton = lv_btn_create(ui_HomeScreen);
    lv_obj_set_width(ui_TestOpenButton, 160);
    lv_obj_set_height(ui_TestOpenButton, 120);
    lv_obj_set_x(ui_TestOpenButton, 160);
    lv_obj_set_y(ui_TestOpenButton, 0);
    lv_obj_add_flag(ui_TestOpenButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_TestOpenButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_TestOpenButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TestOpenButton, lv_color_hex(0x2DA041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TestOpenButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_TestOpenButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_TestOpenButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_TestOpenButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_TestOpenButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TestOpenLabel = lv_label_create(ui_TestOpenButton);
    lv_obj_set_width(ui_TestOpenLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TestOpenLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TestOpenLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TestOpenLabel, "Test");

    ui_SensorMonitorOpenButton = lv_btn_create(ui_HomeScreen);
    lv_obj_set_width(ui_SensorMonitorOpenButton, 160);
    lv_obj_set_height(ui_SensorMonitorOpenButton, 120);
    lv_obj_set_x(ui_SensorMonitorOpenButton, 0);
    lv_obj_set_y(ui_SensorMonitorOpenButton, 120);
    lv_obj_add_flag(ui_SensorMonitorOpenButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SensorMonitorOpenButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SensorMonitorOpenButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SensorMonitorOpenButton, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SensorMonitorOpenButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_SensorMonitorOpenButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_SensorMonitorOpenButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_SensorMonitorOpenButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_SensorMonitorOpenButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SensorMonitorOpenLabel = lv_label_create(ui_SensorMonitorOpenButton);
    lv_obj_set_width(ui_SensorMonitorOpenLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SensorMonitorOpenLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SensorMonitorOpenLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SensorMonitorOpenLabel, "SensorMonitor");

    ui_CommunicationOpenButton = lv_btn_create(ui_HomeScreen);
    lv_obj_set_width(ui_CommunicationOpenButton, 160);
    lv_obj_set_height(ui_CommunicationOpenButton, 120);
    lv_obj_set_x(ui_CommunicationOpenButton, 160);
    lv_obj_set_y(ui_CommunicationOpenButton, 120);
    lv_obj_add_flag(ui_CommunicationOpenButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_CommunicationOpenButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_CommunicationOpenButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CommunicationOpenButton, lv_color_hex(0xEEEA39), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CommunicationOpenButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_CommunicationOpenButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_CommunicationOpenButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_CommunicationOpenButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_CommunicationOpenButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CommunicationOpenLabel = lv_label_create(ui_CommunicationOpenButton);
    lv_obj_set_width(ui_CommunicationOpenLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CommunicationOpenLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CommunicationOpenLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CommunicationOpenLabel, "Communication");

    lv_obj_add_event_cb(ui_ActionOpenButton, ui_event_ActionOpenButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TestOpenButton, ui_event_TestOpenButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SensorMonitorOpenButton, ui_event_SensorMonitorOpenButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CommunicationOpenButton, ui_event_CommunicationOpenButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HomeScreen, ui_event_HomeScreen, LV_EVENT_ALL, NULL);

}

void ui_HomeScreen_screen_destroy(void)
{
    if(ui_HomeScreen) lv_obj_del(ui_HomeScreen);

    // NULL screen variables
    ui_HomeScreen = NULL;
    ui_ActionOpenButton = NULL;
    ui_ActionOpenLabel = NULL;
    ui_TestOpenButton = NULL;
    ui_TestOpenLabel = NULL;
    ui_SensorMonitorOpenButton = NULL;
    ui_SensorMonitorOpenLabel = NULL;
    ui_CommunicationOpenButton = NULL;
    ui_CommunicationOpenLabel = NULL;

}
