// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: test

#include "ui.h"

lv_obj_t * uic_SendButton;
lv_obj_t * uic_LINEScreen;
lv_obj_t * ui_LINEScreen = NULL;
lv_obj_t * ui_DropDown3 = NULL;
lv_obj_t * ui_AppBackButton1 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_Keyboard1 = NULL;
lv_obj_t * ui_TextArea1 = NULL;
lv_obj_t * ui_SendButton = NULL;
lv_obj_t * ui_Label11 = NULL;
// event funtions
void ui_event_AppBackButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_HomeScreen, LV_SCR_LOAD_ANIM_FADE_ON, 10, 0, &ui_HomeScreen_screen_init);
    }
}

// build funtions

void ui_LINEScreen_screen_init(void)
{
    ui_LINEScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_LINEScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DropDown3 = lv_dropdown_create(ui_LINEScreen);
    lv_dropdown_set_dir(ui_DropDown3, LV_DIR_TOP);
    lv_dropdown_set_options(ui_DropDown3, "Send\nReceive");
    lv_obj_set_width(ui_DropDown3, 248);
    lv_obj_set_height(ui_DropDown3, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_x(ui_DropDown3, 2);
    lv_obj_set_y(ui_DropDown3, 3);
    lv_obj_add_flag(ui_DropDown3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_AppBackButton1 = lv_btn_create(ui_LINEScreen);
    lv_obj_set_width(ui_AppBackButton1, 60);
    lv_obj_set_height(ui_AppBackButton1, 35);
    lv_obj_set_x(ui_AppBackButton1, 257);
    lv_obj_set_y(ui_AppBackButton1, 3);
    lv_obj_add_flag(ui_AppBackButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_AppBackButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AppBackButton1, lv_color_hex(0xFF4F4F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AppBackButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_AppBackButton1);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "BACK");

    ui_Keyboard1 = lv_keyboard_create(ui_LINEScreen);
    lv_obj_set_width(ui_Keyboard1, 320);
    lv_obj_set_height(ui_Keyboard1, 140);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_BOTTOM_MID);

    ui_TextArea1 = lv_textarea_create(ui_LINEScreen);
    lv_obj_set_width(ui_TextArea1, 247);
    lv_obj_set_height(ui_TextArea1, 52);
    lv_obj_set_x(ui_TextArea1, 69);
    lv_obj_set_y(ui_TextArea1, 46);
    lv_textarea_set_placeholder_text(ui_TextArea1, "Placeholder...");

    ui_SendButton = lv_btn_create(ui_LINEScreen);
    lv_obj_set_width(ui_SendButton, 60);
    lv_obj_set_height(ui_SendButton, 52);
    lv_obj_set_x(ui_SendButton, 3);
    lv_obj_set_y(ui_SendButton, 46);
    lv_obj_add_flag(ui_SendButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SendButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SendButton, lv_color_hex(0x2DA041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SendButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_SendButton);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "SEND");

    lv_obj_add_event_cb(ui_AppBackButton1, ui_event_AppBackButton1, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard1, ui_TextArea1);
    uic_LINEScreen = ui_LINEScreen;
    uic_SendButton = ui_SendButton;

}

void ui_LINEScreen_screen_destroy(void)
{
    if(ui_LINEScreen) lv_obj_del(ui_LINEScreen);

    // NULL screen variables
    uic_LINEScreen = NULL;
    ui_LINEScreen = NULL;
    ui_DropDown3 = NULL;
    ui_AppBackButton1 = NULL;
    ui_Label9 = NULL;
    ui_Keyboard1 = NULL;
    ui_TextArea1 = NULL;
    uic_SendButton = NULL;
    ui_SendButton = NULL;
    ui_Label11 = NULL;

}
