// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: test

#ifndef UI_LINESCREEN_H
#define UI_LINESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_LINEScreen
extern void ui_LINEScreen_screen_init(void);
extern void ui_LINEScreen_screen_destroy(void);
extern lv_obj_t * ui_LINEScreen;
extern lv_obj_t * ui_DropDown3;
extern void ui_event_AppBackButton1(lv_event_t * e);
extern lv_obj_t * ui_AppBackButton1;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Keyboard1;
extern lv_obj_t * ui_TextArea1;
extern lv_obj_t * ui_SendButton;
extern lv_obj_t * ui_Label11;
// CUSTOM VARIABLES
extern lv_obj_t * uic_LINEScreen;
extern lv_obj_t * uic_SendButton;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

