// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SENSORMONITOR_H
#define UI_SENSORMONITOR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SensorMonitor
extern void ui_SensorMonitor_screen_init(void);
extern void ui_SensorMonitor_screen_destroy(void);
extern void ui_event_SensorMonitor(lv_event_t * e);
extern lv_obj_t * ui_SensorMonitor;
extern lv_obj_t * ui_SensorMonitorTopContainer;
extern void ui_event_SensorMonitorDropdown(lv_event_t * e);
extern lv_obj_t * ui_SensorMonitorDropdown;
extern void ui_event_SensorMonitorBackButton(lv_event_t * e);
extern lv_obj_t * ui_SensorMonitorBackButton;
extern lv_obj_t * ui_SensorMonitorBackLabel2;
extern lv_obj_t * ui_SensorMonitorMidContainer;
extern lv_obj_t * ui_SensorMonitorBallContainer;
extern lv_obj_t * ui_SensorMonitorBallDebugPanel;
extern lv_obj_t * ui_SensorMonitorBallDebugLabel;
extern lv_obj_t * ui_SensorMonitorBallMeterContainerA;
extern lv_obj_t * ui_SensorMonitorBallMeterPanelA;
extern lv_obj_t * ui_SensorMonitorBallMeterButtonA;
extern lv_obj_t * ui_SensorMonitorBallMeterPointorPanelA;
extern lv_obj_t * ui_SensorMonitorBallMeterContainerB;
extern lv_obj_t * ui_SensorMonitorBallMeterPanelB;
extern lv_obj_t * ui_SensorMonitorBallMeterButtonB;
extern lv_obj_t * ui_SensorMonitorBallMeterPointorPanelB;
extern lv_obj_t * ui_SensorMonitorLineContainer;
extern lv_obj_t * ui_SensorMonitorLineDebugPanel;
extern lv_obj_t * ui_SensorMonitorLineDebugLabel;
extern lv_obj_t * ui_SensorMonitorLineMeterContainerA;
extern lv_obj_t * ui_SensorMonitorLineMeterPanelA;
extern lv_obj_t * ui_SensorMonitorLineMeterButtonA;
extern lv_obj_t * ui_SensorMonitorLineMeterPointorPanelA;
extern lv_obj_t * ui_SensorMonitorLineMeterContainerB;
extern lv_obj_t * ui_SensorMonitorLineMeterPanelB;
extern lv_obj_t * ui_SensorMonitorLineMeterButtonB;
extern lv_obj_t * ui_SensorMonitorLineMeterPointorPanelB;
extern lv_obj_t * ui_SensorMonitorGyroContainer;
extern lv_obj_t * ui_SensorMonitorGyroDebugPanel;
extern lv_obj_t * ui_SensorMonitorGyroDebugLabel;
extern lv_obj_t * ui_SensorMonitorGyroMeterContainerA;
extern lv_obj_t * ui_SensorMonitorGyroMeterPanelA;
extern lv_obj_t * ui_SensorMonitorGyroMeterButtonA;
extern lv_obj_t * ui_SensorMonitorGyroMeterPointorPanelA;
extern lv_obj_t * ui_SensorMonitorGyroMeterContainerB;
extern lv_obj_t * ui_SensorMonitorGyroMeterPanelB;
extern lv_obj_t * ui_SensorMonitorGyroMeterButtonB;
extern lv_obj_t * ui_SensorMonitorGyroMeterPointorPanelB;
extern lv_obj_t * ui_SensorMonitorGoalContainer;
extern lv_obj_t * ui_SensorMonitorGoalDebugPanel;
extern lv_obj_t * ui_SensorMonitorGoalDebugLabel;
extern lv_obj_t * ui_SensorMonitorGoalMeterContainerA;
extern lv_obj_t * ui_SensorMonitorGoalMeterPanelA;
extern lv_obj_t * ui_SensorMonitorGoalMeterButtonA;
extern lv_obj_t * ui_SensorMonitorGoalMeterPointorPanelA;
extern lv_obj_t * ui_SensorMonitorGoalMeterContainerB;
extern lv_obj_t * ui_SensorMonitorGoalMeterPanelB;
extern lv_obj_t * ui_SensorMonitorGoalMeterButtonB;
extern lv_obj_t * ui_SensorMonitorGoalMeterPointorPanelB;
extern lv_obj_t * ui_SensorMonitorLidarContainer;
extern lv_obj_t * ui_SensorMonitorLidarDebugPanel;
extern lv_obj_t * ui_SensorMonitorLidarDebugLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

