// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SENSORMONITOR_H
#define UI_SENSORMONITOR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SensorMonitor
extern void ui_SensorMonitor_screen_init(void);
extern void ui_SensorMonitor_screen_destroy(void);
extern lv_obj_t * ui_SensorMonitor;
extern lv_obj_t * ui_SensorMonitorTopContainer;
extern lv_obj_t * ui_SensorMonitorDropdown;
extern void ui_event_SensorMonitorBackButton(lv_event_t * e);
extern lv_obj_t * ui_SensorMonitorBackButton;
extern lv_obj_t * ui_SensorMonitorBackLabel2;
extern lv_obj_t * ui_SensorMonitorMidContainer;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

