// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: test

#include "ui.h"

lv_obj_t * uic_AppBackButton2;
lv_obj_t * uic_DropDown2;
lv_obj_t * uic_SensorCheckAppScreen;
lv_obj_t * ui_SensorCheckAppScreen = NULL;
lv_obj_t * ui_DropDown2 = NULL;
lv_obj_t * ui_AppBackButton2 = NULL;
lv_obj_t * ui_Label6 = NULL;
// event funtions
void ui_event_AppBackButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_HomeScreen, LV_SCR_LOAD_ANIM_FADE_ON, 10, 0, &ui_HomeScreen_screen_init);
    }
}

// build funtions

void ui_SensorCheckAppScreen_screen_init(void)
{
    ui_SensorCheckAppScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SensorCheckAppScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DropDown2 = lv_dropdown_create(ui_SensorCheckAppScreen);
    lv_dropdown_set_dir(ui_DropDown2, LV_DIR_TOP);
    lv_dropdown_set_options(ui_DropDown2, "Kicker\nDribbler\nBno\nCam");
    lv_obj_set_width(ui_DropDown2, 248);
    lv_obj_set_height(ui_DropDown2, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_x(ui_DropDown2, 2);
    lv_obj_set_y(ui_DropDown2, 3);
    lv_obj_add_flag(ui_DropDown2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_AppBackButton2 = lv_btn_create(ui_SensorCheckAppScreen);
    lv_obj_set_width(ui_AppBackButton2, 60);
    lv_obj_set_height(ui_AppBackButton2, 35);
    lv_obj_set_x(ui_AppBackButton2, 257);
    lv_obj_set_y(ui_AppBackButton2, 3);
    lv_obj_add_flag(ui_AppBackButton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_AppBackButton2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AppBackButton2, lv_color_hex(0xFF4F4F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AppBackButton2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_AppBackButton2);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "BACK");

    lv_obj_add_event_cb(ui_AppBackButton2, ui_event_AppBackButton2, LV_EVENT_ALL, NULL);
    uic_SensorCheckAppScreen = ui_SensorCheckAppScreen;
    uic_DropDown2 = ui_DropDown2;
    uic_AppBackButton2 = ui_AppBackButton2;

}

void ui_SensorCheckAppScreen_screen_destroy(void)
{
    if(ui_SensorCheckAppScreen) lv_obj_del(ui_SensorCheckAppScreen);

    // NULL screen variables
    uic_SensorCheckAppScreen = NULL;
    ui_SensorCheckAppScreen = NULL;
    uic_DropDown2 = NULL;
    ui_DropDown2 = NULL;
    uic_AppBackButton2 = NULL;
    ui_AppBackButton2 = NULL;
    ui_Label6 = NULL;

}
