// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: test

#ifndef UI_SENSORCHECKAPPSCREEN_H
#define UI_SENSORCHECKAPPSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SensorCheckAppScreen
extern void ui_SensorCheckAppScreen_screen_init(void);
extern void ui_SensorCheckAppScreen_screen_destroy(void);
extern lv_obj_t * ui_SensorCheckAppScreen;
extern void ui_event_DropDown2(lv_event_t * e);
extern lv_obj_t * ui_DropDown2;
extern void ui_event_AppBackButton2(lv_event_t * e);
extern lv_obj_t * ui_AppBackButton2;
extern lv_obj_t * ui_Label6;
// CUSTOM VARIABLES
extern lv_obj_t * uic_SensorCheckAppScreen;
extern lv_obj_t * uic_DropDown2;
extern lv_obj_t * uic_AppBackButton2;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

