// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SENSORMONITOR_H
#define UI_SENSORMONITOR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SensorMonitor
extern void ui_SensorMonitor_screen_init(void);
extern void ui_SensorMonitor_screen_destroy(void);
extern void ui_event_SensorMonitor(lv_event_t * e);
extern lv_obj_t * ui_SensorMonitor;
extern lv_obj_t * ui_SensorMonitorTopContainer;
extern void ui_event_SensorMonitorDropdown(lv_event_t * e);
extern lv_obj_t * ui_SensorMonitorDropdown;
extern void ui_event_SensorMonitorBackButton(lv_event_t * e);
extern lv_obj_t * ui_SensorMonitorBackButton;
extern lv_obj_t * ui_SensorMonitorBackLabel2;
extern lv_obj_t * ui_SensorMonitorMidContainer;
extern lv_obj_t * ui_SensorMonitorBallContainer;
extern lv_obj_t * ui_SensorMonitorBallDebugPanel;
extern lv_obj_t * ui_SensorMonitorBallDebugLabel;
extern lv_obj_t * ui_SensorMonitorBallMeterContainer1;
extern lv_obj_t * ui_SensorMonitorBallMeterPanel1;
extern lv_obj_t * ui_SensorMonitorBallMeterButton1;
extern lv_obj_t * ui_SensorMonitorBallMeterPointorPanel1;
extern lv_obj_t * ui_SensorMonitorBallMeterContainer2;
extern lv_obj_t * ui_SensorMonitorBallMeterPanel2;
extern lv_obj_t * ui_SensorMonitorBallMeterButton2;
extern lv_obj_t * ui_SensorMonitorBallMeterPointorPanel2;
extern lv_obj_t * ui_SensorMonitorLineContainer;
extern lv_obj_t * ui_SensorMonitorLineDebugPanel;
extern lv_obj_t * ui_SensorMonitorLineDebugLabel;
extern lv_obj_t * ui_SensorMonitorLineMeterContainer1;
extern lv_obj_t * ui_SensorMonitorLineMeterPanel1;
extern lv_obj_t * ui_SensorMonitorLineMeterButton1;
extern lv_obj_t * ui_SensorMonitorLineMeterPointorPanel1;
extern lv_obj_t * ui_SensorMonitorLineMeterContainer2;
extern lv_obj_t * ui_SensorMonitorLineMeterPanel2;
extern lv_obj_t * ui_SensorMonitorLineMeterButton2;
extern lv_obj_t * ui_SensorMonitorLineMeterPointorPanel2;
extern lv_obj_t * ui_SensorMonitorGyroContainer;
extern lv_obj_t * ui_SensorMonitorGyroDebugPanel;
extern lv_obj_t * ui_SensorMonitorBallDebugLabel2;
extern lv_obj_t * ui_SensorMonitorGyroMeterContainer1;
extern lv_obj_t * ui_SensorMonitorGyroMeterPanel1;
extern lv_obj_t * ui_SensorMonitorGyroMeterButton1;
extern lv_obj_t * ui_SensorMonitorGyroMeterPointorPanel1;
extern lv_obj_t * ui_SensorMonitorGyroMeterContainer2;
extern lv_obj_t * ui_SensorMonitorGyroMeterPanel2;
extern lv_obj_t * ui_SensorMonitorGyroMeterButton2;
extern lv_obj_t * ui_SensorMonitorGyroMeterPointorPanel2;
extern lv_obj_t * ui_SensorMonitorGoalContainer;
extern lv_obj_t * ui_SensorMonitorGoalDebugPanel;
extern lv_obj_t * ui_SensorMonitorGoalDebugLabel;
extern lv_obj_t * ui_SensorMonitorGoalMeterContainer1;
extern lv_obj_t * ui_SensorMonitorGoalMeterPanel1;
extern lv_obj_t * ui_SensorMonitorGoalMeterButton1;
extern lv_obj_t * ui_SensorMonitorGoalMeterPointorPanel1;
extern lv_obj_t * ui_SensorMonitorGoalMeterContainer2;
extern lv_obj_t * ui_SensorMonitorGoalMeterPanel2;
extern lv_obj_t * ui_SensorMonitorGoalMeterButton2;
extern lv_obj_t * ui_SensorMonitorGoalMeterPointorPanel2;
extern lv_obj_t * ui_SensorMonitorLidarContainer;
extern lv_obj_t * ui_SensorMonitorLidarDebugPanel;
extern lv_obj_t * ui_SensorMonitorLidarDebugLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

