// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_SensorMonitor = NULL;
lv_obj_t * ui_SensorMonitorTopContainer = NULL;
lv_obj_t * ui_SensorMonitorDropdown = NULL;
lv_obj_t * ui_SensorMonitorBackButton = NULL;
lv_obj_t * ui_SensorMonitorBackLabel2 = NULL;
lv_obj_t * ui_SensorMonitorMidContainer = NULL;
// event funtions
void ui_event_SensorMonitorBackButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_HomeScreen, LV_SCR_LOAD_ANIM_FADE_ON, 10, 0, &ui_HomeScreen_screen_init);
    }
}

// build funtions

void ui_SensorMonitor_screen_init(void)
{
    ui_SensorMonitor = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SensorMonitor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SensorMonitorTopContainer = lv_obj_create(ui_SensorMonitor);
    lv_obj_remove_style_all(ui_SensorMonitorTopContainer);
    lv_obj_set_width(ui_SensorMonitorTopContainer, 320);
    lv_obj_set_height(ui_SensorMonitorTopContainer, 40);
    lv_obj_clear_flag(ui_SensorMonitorTopContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SensorMonitorDropdown = lv_dropdown_create(ui_SensorMonitorTopContainer);
    lv_dropdown_set_options(ui_SensorMonitorDropdown, "Ball\nLine\nGyro\nGoal\nLidar");
    lv_obj_set_width(ui_SensorMonitorDropdown, 258);
    lv_obj_set_height(ui_SensorMonitorDropdown, 38);
    lv_obj_set_x(ui_SensorMonitorDropdown, 1);
    lv_obj_set_y(ui_SensorMonitorDropdown, 1);
    lv_obj_add_flag(ui_SensorMonitorDropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_SensorMonitorBackButton = lv_btn_create(ui_SensorMonitorTopContainer);
    lv_obj_set_width(ui_SensorMonitorBackButton, 58);
    lv_obj_set_height(ui_SensorMonitorBackButton, 38);
    lv_obj_set_x(ui_SensorMonitorBackButton, 261);
    lv_obj_set_y(ui_SensorMonitorBackButton, 1);
    lv_obj_add_flag(ui_SensorMonitorBackButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SensorMonitorBackButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SensorMonitorBackButton, lv_color_hex(0xFF3333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SensorMonitorBackButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_SensorMonitorBackButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_SensorMonitorBackButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_SensorMonitorBackButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_SensorMonitorBackButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SensorMonitorBackLabel2 = lv_label_create(ui_SensorMonitorBackButton);
    lv_obj_set_width(ui_SensorMonitorBackLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SensorMonitorBackLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SensorMonitorBackLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SensorMonitorBackLabel2, "Back");
    lv_obj_set_style_text_color(ui_SensorMonitorBackLabel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SensorMonitorBackLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_SensorMonitorBackLabel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_SensorMonitorBackLabel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_SensorMonitorBackLabel2, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_SensorMonitorBackLabel2, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SensorMonitorBackLabel2, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SensorMonitorMidContainer = lv_obj_create(ui_SensorMonitor);
    lv_obj_remove_style_all(ui_SensorMonitorMidContainer);
    lv_obj_set_width(ui_SensorMonitorMidContainer, 320);
    lv_obj_set_height(ui_SensorMonitorMidContainer, 200);
    lv_obj_set_x(ui_SensorMonitorMidContainer, 0);
    lv_obj_set_y(ui_SensorMonitorMidContainer, 40);
    lv_obj_clear_flag(ui_SensorMonitorMidContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_SensorMonitorBackButton, ui_event_SensorMonitorBackButton, LV_EVENT_ALL, NULL);

}

void ui_SensorMonitor_screen_destroy(void)
{
    if(ui_SensorMonitor) lv_obj_del(ui_SensorMonitor);

    // NULL screen variables
    ui_SensorMonitor = NULL;
    ui_SensorMonitorTopContainer = NULL;
    ui_SensorMonitorDropdown = NULL;
    ui_SensorMonitorBackButton = NULL;
    ui_SensorMonitorBackLabel2 = NULL;
    ui_SensorMonitorMidContainer = NULL;

}
