// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Test = NULL;
lv_obj_t * ui_TestTopContainer = NULL;
lv_obj_t * ui_TestDropdown = NULL;
lv_obj_t * ui_TestBackButton = NULL;
lv_obj_t * ui_TestBackLabel = NULL;
lv_obj_t * ui_TestMidContainer = NULL;
lv_obj_t * ui_TestKickerContainer = NULL;
lv_obj_t * ui_TestKickerLeverContainer = NULL;
lv_obj_t * ui_TestKickerLeverRearButton = NULL;
lv_obj_t * ui_TestKickerLeverRearLabel = NULL;
lv_obj_t * ui_TestKickerLeverFrontButton = NULL;
lv_obj_t * ui_TestKickerLeverFrontLabel = NULL;
lv_obj_t * ui_TestKickerKickButton = NULL;
lv_obj_t * ui_TestKickerKickLabel = NULL;
lv_obj_t * ui_TestKickerDebugPanel = NULL;
lv_obj_t * ui_TestKickerDebugLabel = NULL;
lv_obj_t * ui_TestDribblerContainer = NULL;
lv_obj_t * ui_TestDribblerLeverContainer1 = NULL;
lv_obj_t * ui_TestDribblerLeverRearButton = NULL;
lv_obj_t * ui_TestDribblerLeverRearLabel = NULL;
lv_obj_t * ui_TestDribblerLeverFrontButton = NULL;
lv_obj_t * ui_TestDribblerLeverFrontLabel = NULL;
lv_obj_t * ui_TestDribblerLeverContainer2 = NULL;
lv_obj_t * ui_TestDribblerLeverRunButton = NULL;
lv_obj_t * ui_TestDribblerLeverRunLabel = NULL;
lv_obj_t * ui_TestDribblerLeverIdleButton = NULL;
lv_obj_t * ui_TestDribblerLeverIdleLabel = NULL;
lv_obj_t * ui_TestDribblerDebugPanel = NULL;
lv_obj_t * ui_TestDribblerDebugLabel = NULL;
lv_obj_t * ui_TestMotorContainer = NULL;
lv_obj_t * ui_TestMotorLeverContainer = NULL;
lv_obj_t * ui_TestMotorLeverRunButton = NULL;
lv_obj_t * ui_TestMotorLeverRunLabel = NULL;
lv_obj_t * ui_TestMotorLeverIdleButton = NULL;
lv_obj_t * ui_TestMotorLeverIdleLabel = NULL;
lv_obj_t * ui_TestMotorMeterContainer = NULL;
lv_obj_t * ui_TestMotorMeterPanel = NULL;
lv_obj_t * ui_TestMotorMeterButton = NULL;
lv_obj_t * ui_TestMotorMeterPointorPanel = NULL;
lv_obj_t * ui_TestMotorConfigContainer = NULL;
lv_obj_t * ui_TestMotorConfigCheckbox1 = NULL;
lv_obj_t * ui_TestMotorConfigCheckbox2 = NULL;
lv_obj_t * ui_TestMotorConfigCheckbox3 = NULL;
lv_obj_t * ui_TestMotorConfigCheckbox4 = NULL;
lv_obj_t * ui_TestMotorDebugPanel = NULL;
lv_obj_t * ui_TestMotorDebugLabel = NULL;
// event funtions
void ui_event_Test(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        test_loaded_event(e);
    }
}

void ui_event_TestDropdown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        test_dropdown_value_changed_event(e);
    }
}

void ui_event_TestBackButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_HomeScreen, LV_SCR_LOAD_ANIM_FADE_ON, 10, 0, &ui_HomeScreen_screen_init);
    }
}

void ui_event_TestKickerLeverRearButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_TestKickerLeverRearButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_TestKickerLeverFrontButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

void ui_event_TestKickerLeverFrontButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_TestKickerLeverRearButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_TestKickerLeverFrontButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

void ui_event_TestDribblerLeverRearButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_TestDribblerLeverRearButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_TestDribblerLeverFrontButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

void ui_event_TestDribblerLeverFrontButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_TestDribblerLeverRearButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_TestDribblerLeverFrontButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

void ui_event_TestDribblerLeverRunButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_TestDribblerLeverIdleButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_TestDribblerLeverRunButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

void ui_event_TestDribblerLeverIdleButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_TestDribblerLeverIdleButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_TestDribblerLeverRunButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

void ui_event_TestMotorLeverRunButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_TestMotorLeverIdleButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_TestMotorLeverRunButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

void ui_event_TestMotorLeverIdleButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_TestMotorLeverIdleButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_TestMotorLeverRunButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

void ui_event_TestMotorMeterButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        testmotor_meter_switch_event(e);
    }
}

// build funtions

void ui_Test_screen_init(void)
{
    ui_Test = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Test, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TestTopContainer = lv_obj_create(ui_Test);
    lv_obj_remove_style_all(ui_TestTopContainer);
    lv_obj_set_width(ui_TestTopContainer, 320);
    lv_obj_set_height(ui_TestTopContainer, 40);
    lv_obj_clear_flag(ui_TestTopContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TestDropdown = lv_dropdown_create(ui_TestTopContainer);
    lv_dropdown_set_options(ui_TestDropdown, "Kicker\nDribbler\nMotor");
    lv_obj_set_width(ui_TestDropdown, 258);
    lv_obj_set_height(ui_TestDropdown, 38);
    lv_obj_set_x(ui_TestDropdown, 1);
    lv_obj_set_y(ui_TestDropdown, 1);
    lv_obj_add_flag(ui_TestDropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_TestBackButton = lv_btn_create(ui_TestTopContainer);
    lv_obj_set_width(ui_TestBackButton, 58);
    lv_obj_set_height(ui_TestBackButton, 38);
    lv_obj_set_x(ui_TestBackButton, 261);
    lv_obj_set_y(ui_TestBackButton, 1);
    lv_obj_add_flag(ui_TestBackButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_TestBackButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TestBackButton, lv_color_hex(0xFF3333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TestBackButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_TestBackButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_TestBackButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_TestBackButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_TestBackButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TestBackLabel = lv_label_create(ui_TestBackButton);
    lv_obj_set_width(ui_TestBackLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TestBackLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TestBackLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TestBackLabel, "Back");
    lv_obj_set_style_text_color(ui_TestBackLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TestBackLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_TestBackLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_TestBackLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TestBackLabel, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_TestBackLabel, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TestBackLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TestMidContainer = lv_obj_create(ui_Test);
    lv_obj_remove_style_all(ui_TestMidContainer);
    lv_obj_set_width(ui_TestMidContainer, 320);
    lv_obj_set_height(ui_TestMidContainer, 200);
    lv_obj_set_x(ui_TestMidContainer, 0);
    lv_obj_set_y(ui_TestMidContainer, 40);
    lv_obj_clear_flag(ui_TestMidContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TestKickerContainer = lv_obj_create(ui_TestMidContainer);
    lv_obj_remove_style_all(ui_TestKickerContainer);
    lv_obj_set_width(ui_TestKickerContainer, 320);
    lv_obj_set_height(ui_TestKickerContainer, 200);
    lv_obj_add_flag(ui_TestKickerContainer, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_TestKickerContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TestKickerLeverContainer = lv_obj_create(ui_TestKickerContainer);
    lv_obj_remove_style_all(ui_TestKickerLeverContainer);
    lv_obj_set_width(ui_TestKickerLeverContainer, 100);
    lv_obj_set_height(ui_TestKickerLeverContainer, 100);
    lv_obj_set_x(ui_TestKickerLeverContainer, -1);
    lv_obj_set_y(ui_TestKickerLeverContainer, 1);
    lv_obj_set_align(ui_TestKickerLeverContainer, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_TestKickerLeverContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TestKickerLeverRearButton = lv_btn_create(ui_TestKickerLeverContainer);
    lv_obj_set_width(ui_TestKickerLeverRearButton, 98);
    lv_obj_set_height(ui_TestKickerLeverRearButton, 98);
    lv_obj_set_align(ui_TestKickerLeverRearButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TestKickerLeverRearButton, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_TestKickerLeverRearButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TestKickerLeverRearButton, lv_color_hex(0x565656), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TestKickerLeverRearButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_TestKickerLeverRearButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_TestKickerLeverRearButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_TestKickerLeverRearButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_TestKickerLeverRearButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TestKickerLeverRearLabel = lv_label_create(ui_TestKickerLeverRearButton);
    lv_obj_set_width(ui_TestKickerLeverRearLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TestKickerLeverRearLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TestKickerLeverRearLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TestKickerLeverRearLabel, "Rear");
    lv_obj_set_style_text_color(ui_TestKickerLeverRearLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TestKickerLeverRearLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_TestKickerLeverRearLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_TestKickerLeverRearLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TestKickerLeverRearLabel, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_TestKickerLeverRearLabel, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TestKickerLeverRearLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TestKickerLeverFrontButton = lv_btn_create(ui_TestKickerLeverContainer);
    lv_obj_set_width(ui_TestKickerLeverFrontButton, 98);
    lv_obj_set_height(ui_TestKickerLeverFrontButton, 98);
    lv_obj_set_align(ui_TestKickerLeverFrontButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TestKickerLeverFrontButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_TestKickerLeverFrontButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TestKickerLeverFrontButton, lv_color_hex(0x565656), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TestKickerLeverFrontButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_TestKickerLeverFrontButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_TestKickerLeverFrontButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_TestKickerLeverFrontButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_TestKickerLeverFrontButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TestKickerLeverFrontLabel = lv_label_create(ui_TestKickerLeverFrontButton);
    lv_obj_set_width(ui_TestKickerLeverFrontLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TestKickerLeverFrontLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TestKickerLeverFrontLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TestKickerLeverFrontLabel, "Front");
    lv_obj_set_style_text_color(ui_TestKickerLeverFrontLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TestKickerLeverFrontLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_TestKickerLeverFrontLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_TestKickerLeverFrontLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TestKickerLeverFrontLabel, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_TestKickerLeverFrontLabel, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TestKickerLeverFrontLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TestKickerKickButton = lv_btn_create(ui_TestKickerContainer);
    lv_obj_set_width(ui_TestKickerKickButton, 216);
    lv_obj_set_height(ui_TestKickerKickButton, 98);
    lv_obj_set_x(ui_TestKickerKickButton, 2);
    lv_obj_set_y(ui_TestKickerKickButton, 2);
    lv_obj_add_flag(ui_TestKickerKickButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_TestKickerKickButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TestKickerKickButton, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TestKickerKickButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_TestKickerKickButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_TestKickerKickButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_TestKickerKickButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_TestKickerKickButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TestKickerKickLabel = lv_label_create(ui_TestKickerKickButton);
    lv_obj_set_width(ui_TestKickerKickLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TestKickerKickLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TestKickerKickLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TestKickerKickLabel, "Kick");
    lv_obj_set_style_text_color(ui_TestKickerKickLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TestKickerKickLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_TestKickerKickLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_TestKickerKickLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TestKickerKickLabel, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_TestKickerKickLabel, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TestKickerKickLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TestKickerDebugPanel = lv_obj_create(ui_TestKickerContainer);
    lv_obj_set_width(ui_TestKickerDebugPanel, 318);
    lv_obj_set_height(ui_TestKickerDebugPanel, 96);
    lv_obj_set_x(ui_TestKickerDebugPanel, 1);
    lv_obj_set_y(ui_TestKickerDebugPanel, -1);
    lv_obj_set_align(ui_TestKickerDebugPanel, LV_ALIGN_BOTTOM_LEFT);

    ui_TestKickerDebugLabel = lv_label_create(ui_TestKickerDebugPanel);
    lv_obj_set_width(ui_TestKickerDebugLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TestKickerDebugLabel, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_TestKickerDebugLabel, "FrontCatch : true\nBackCatch : false");

    ui_TestDribblerContainer = lv_obj_create(ui_TestMidContainer);
    lv_obj_remove_style_all(ui_TestDribblerContainer);
    lv_obj_set_width(ui_TestDribblerContainer, 320);
    lv_obj_set_height(ui_TestDribblerContainer, 200);
    lv_obj_add_flag(ui_TestDribblerContainer, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_TestDribblerContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TestDribblerLeverContainer1 = lv_obj_create(ui_TestDribblerContainer);
    lv_obj_remove_style_all(ui_TestDribblerLeverContainer1);
    lv_obj_set_width(ui_TestDribblerLeverContainer1, 100);
    lv_obj_set_height(ui_TestDribblerLeverContainer1, 100);
    lv_obj_set_x(ui_TestDribblerLeverContainer1, -1);
    lv_obj_set_y(ui_TestDribblerLeverContainer1, 1);
    lv_obj_set_align(ui_TestDribblerLeverContainer1, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_TestDribblerLeverContainer1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TestDribblerLeverRearButton = lv_btn_create(ui_TestDribblerLeverContainer1);
    lv_obj_set_width(ui_TestDribblerLeverRearButton, 98);
    lv_obj_set_height(ui_TestDribblerLeverRearButton, 98);
    lv_obj_set_align(ui_TestDribblerLeverRearButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TestDribblerLeverRearButton, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_TestDribblerLeverRearButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TestDribblerLeverRearButton, lv_color_hex(0x565656), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TestDribblerLeverRearButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_TestDribblerLeverRearButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_TestDribblerLeverRearButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_TestDribblerLeverRearButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_TestDribblerLeverRearButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TestDribblerLeverRearLabel = lv_label_create(ui_TestDribblerLeverRearButton);
    lv_obj_set_width(ui_TestDribblerLeverRearLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TestDribblerLeverRearLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TestDribblerLeverRearLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TestDribblerLeverRearLabel, "Rear");
    lv_obj_set_style_text_color(ui_TestDribblerLeverRearLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TestDribblerLeverRearLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_TestDribblerLeverRearLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_TestDribblerLeverRearLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TestDribblerLeverRearLabel, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_TestDribblerLeverRearLabel, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TestDribblerLeverRearLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TestDribblerLeverFrontButton = lv_btn_create(ui_TestDribblerLeverContainer1);
    lv_obj_set_width(ui_TestDribblerLeverFrontButton, 98);
    lv_obj_set_height(ui_TestDribblerLeverFrontButton, 98);
    lv_obj_set_align(ui_TestDribblerLeverFrontButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TestDribblerLeverFrontButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_TestDribblerLeverFrontButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TestDribblerLeverFrontButton, lv_color_hex(0x565656), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TestDribblerLeverFrontButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_TestDribblerLeverFrontButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_TestDribblerLeverFrontButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_TestDribblerLeverFrontButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_TestDribblerLeverFrontButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TestDribblerLeverFrontLabel = lv_label_create(ui_TestDribblerLeverFrontButton);
    lv_obj_set_width(ui_TestDribblerLeverFrontLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TestDribblerLeverFrontLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TestDribblerLeverFrontLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TestDribblerLeverFrontLabel, "Front");
    lv_obj_set_style_text_color(ui_TestDribblerLeverFrontLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TestDribblerLeverFrontLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_TestDribblerLeverFrontLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_TestDribblerLeverFrontLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TestDribblerLeverFrontLabel, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_TestDribblerLeverFrontLabel, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TestDribblerLeverFrontLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TestDribblerLeverContainer2 = lv_obj_create(ui_TestDribblerContainer);
    lv_obj_remove_style_all(ui_TestDribblerLeverContainer2);
    lv_obj_set_width(ui_TestDribblerLeverContainer2, 216);
    lv_obj_set_height(ui_TestDribblerLeverContainer2, 100);
    lv_obj_set_x(ui_TestDribblerLeverContainer2, 1);
    lv_obj_set_y(ui_TestDribblerLeverContainer2, 1);
    lv_obj_clear_flag(ui_TestDribblerLeverContainer2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TestDribblerLeverRunButton = lv_btn_create(ui_TestDribblerLeverContainer2);
    lv_obj_set_width(ui_TestDribblerLeverRunButton, 216);
    lv_obj_set_height(ui_TestDribblerLeverRunButton, 98);
    lv_obj_set_align(ui_TestDribblerLeverRunButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TestDribblerLeverRunButton, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_TestDribblerLeverRunButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TestDribblerLeverRunButton, lv_color_hex(0x2DA041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TestDribblerLeverRunButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_TestDribblerLeverRunButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_TestDribblerLeverRunButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_TestDribblerLeverRunButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_TestDribblerLeverRunButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TestDribblerLeverRunLabel = lv_label_create(ui_TestDribblerLeverRunButton);
    lv_obj_set_width(ui_TestDribblerLeverRunLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TestDribblerLeverRunLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TestDribblerLeverRunLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TestDribblerLeverRunLabel, "Run");
    lv_obj_set_style_text_color(ui_TestDribblerLeverRunLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TestDribblerLeverRunLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_TestDribblerLeverRunLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_TestDribblerLeverRunLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TestDribblerLeverRunLabel, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_TestDribblerLeverRunLabel, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TestDribblerLeverRunLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TestDribblerLeverIdleButton = lv_btn_create(ui_TestDribblerLeverContainer2);
    lv_obj_set_width(ui_TestDribblerLeverIdleButton, 216);
    lv_obj_set_height(ui_TestDribblerLeverIdleButton, 98);
    lv_obj_set_align(ui_TestDribblerLeverIdleButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TestDribblerLeverIdleButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_TestDribblerLeverIdleButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TestDribblerLeverIdleButton, lv_color_hex(0x565656), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TestDribblerLeverIdleButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_TestDribblerLeverIdleButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_TestDribblerLeverIdleButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_TestDribblerLeverIdleButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_TestDribblerLeverIdleButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TestDribblerLeverIdleLabel = lv_label_create(ui_TestDribblerLeverIdleButton);
    lv_obj_set_width(ui_TestDribblerLeverIdleLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TestDribblerLeverIdleLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TestDribblerLeverIdleLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TestDribblerLeverIdleLabel, "Idle");
    lv_obj_set_style_text_color(ui_TestDribblerLeverIdleLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TestDribblerLeverIdleLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_TestDribblerLeverIdleLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_TestDribblerLeverIdleLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TestDribblerLeverIdleLabel, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_TestDribblerLeverIdleLabel, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TestDribblerLeverIdleLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TestDribblerDebugPanel = lv_obj_create(ui_TestDribblerContainer);
    lv_obj_set_width(ui_TestDribblerDebugPanel, 318);
    lv_obj_set_height(ui_TestDribblerDebugPanel, 96);
    lv_obj_set_x(ui_TestDribblerDebugPanel, 1);
    lv_obj_set_y(ui_TestDribblerDebugPanel, -1);
    lv_obj_set_align(ui_TestDribblerDebugPanel, LV_ALIGN_BOTTOM_LEFT);

    ui_TestDribblerDebugLabel = lv_label_create(ui_TestDribblerDebugPanel);
    lv_obj_set_width(ui_TestDribblerDebugLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TestDribblerDebugLabel, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_TestDribblerDebugLabel, "FrontCatch : true\nBackCatch : false");

    ui_TestMotorContainer = lv_obj_create(ui_TestMidContainer);
    lv_obj_remove_style_all(ui_TestMotorContainer);
    lv_obj_set_width(ui_TestMotorContainer, 320);
    lv_obj_set_height(ui_TestMotorContainer, 200);
    lv_obj_clear_flag(ui_TestMotorContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TestMotorLeverContainer = lv_obj_create(ui_TestMotorContainer);
    lv_obj_remove_style_all(ui_TestMotorLeverContainer);
    lv_obj_set_width(ui_TestMotorLeverContainer, 100);
    lv_obj_set_height(ui_TestMotorLeverContainer, 100);
    lv_obj_set_x(ui_TestMotorLeverContainer, 1);
    lv_obj_set_y(ui_TestMotorLeverContainer, 1);
    lv_obj_clear_flag(ui_TestMotorLeverContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TestMotorLeverRunButton = lv_btn_create(ui_TestMotorLeverContainer);
    lv_obj_set_width(ui_TestMotorLeverRunButton, 98);
    lv_obj_set_height(ui_TestMotorLeverRunButton, 98);
    lv_obj_set_align(ui_TestMotorLeverRunButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TestMotorLeverRunButton, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_TestMotorLeverRunButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TestMotorLeverRunButton, lv_color_hex(0x2DA041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TestMotorLeverRunButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_TestMotorLeverRunButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_TestMotorLeverRunButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_TestMotorLeverRunButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_TestMotorLeverRunButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TestMotorLeverRunLabel = lv_label_create(ui_TestMotorLeverRunButton);
    lv_obj_set_width(ui_TestMotorLeverRunLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TestMotorLeverRunLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TestMotorLeverRunLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TestMotorLeverRunLabel, "Run");
    lv_obj_set_style_text_color(ui_TestMotorLeverRunLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TestMotorLeverRunLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_TestMotorLeverRunLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_TestMotorLeverRunLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TestMotorLeverRunLabel, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_TestMotorLeverRunLabel, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TestMotorLeverRunLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TestMotorLeverIdleButton = lv_btn_create(ui_TestMotorLeverContainer);
    lv_obj_set_width(ui_TestMotorLeverIdleButton, 98);
    lv_obj_set_height(ui_TestMotorLeverIdleButton, 98);
    lv_obj_set_align(ui_TestMotorLeverIdleButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TestMotorLeverIdleButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_TestMotorLeverIdleButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TestMotorLeverIdleButton, lv_color_hex(0x565656), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TestMotorLeverIdleButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_TestMotorLeverIdleButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_TestMotorLeverIdleButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_TestMotorLeverIdleButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_TestMotorLeverIdleButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TestMotorLeverIdleLabel = lv_label_create(ui_TestMotorLeverIdleButton);
    lv_obj_set_width(ui_TestMotorLeverIdleLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TestMotorLeverIdleLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TestMotorLeverIdleLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TestMotorLeverIdleLabel, "Idle");
    lv_obj_set_style_text_color(ui_TestMotorLeverIdleLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TestMotorLeverIdleLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_TestMotorLeverIdleLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_TestMotorLeverIdleLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TestMotorLeverIdleLabel, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_TestMotorLeverIdleLabel, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TestMotorLeverIdleLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TestMotorMeterContainer = lv_obj_create(ui_TestMotorContainer);
    lv_obj_remove_style_all(ui_TestMotorMeterContainer);
    lv_obj_set_width(ui_TestMotorMeterContainer, 100);
    lv_obj_set_height(ui_TestMotorMeterContainer, 100);
    lv_obj_set_x(ui_TestMotorMeterContainer, -2);
    lv_obj_set_y(ui_TestMotorMeterContainer, 2);
    lv_obj_set_align(ui_TestMotorMeterContainer, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_TestMotorMeterContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TestMotorMeterPanel = lv_obj_create(ui_TestMotorMeterContainer);
    lv_obj_set_width(ui_TestMotorMeterPanel, 93);
    lv_obj_set_height(ui_TestMotorMeterPanel, 93);
    lv_obj_set_align(ui_TestMotorMeterPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TestMotorMeterPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_TestMotorMeterPanel, 47, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TestMotorMeterPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TestMotorMeterPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TestMotorMeterPanel, lv_color_hex(0x565656), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TestMotorMeterPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TestMotorMeterPanel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TestMotorMeterButton = lv_btn_create(ui_TestMotorMeterPanel);
    lv_obj_set_width(ui_TestMotorMeterButton, 70);
    lv_obj_set_height(ui_TestMotorMeterButton, 70);
    lv_obj_set_align(ui_TestMotorMeterButton, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_TestMotorMeterButton, LV_STATE_USER_1);       /// States
    lv_obj_add_flag(ui_TestMotorMeterButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_TestMotorMeterButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_TestMotorMeterButton, 35, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_TestMotorMeterButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_TestMotorMeterButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_TestMotorMeterButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_TestMotorMeterButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TestMotorMeterButton, lv_color_hex(0xE8E839), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_opa(ui_TestMotorMeterButton, 255, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_color(ui_TestMotorMeterButton, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_bg_opa(ui_TestMotorMeterButton, 255, LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_bg_color(ui_TestMotorMeterButton, lv_color_hex(0x525552), LV_PART_MAIN | LV_STATE_USER_3);
    lv_obj_set_style_bg_opa(ui_TestMotorMeterButton, 255, LV_PART_MAIN | LV_STATE_USER_3);

    ui_TestMotorMeterPointorPanel = lv_obj_create(ui_TestMotorMeterContainer);
    lv_obj_set_width(ui_TestMotorMeterPointorPanel, 12);
    lv_obj_set_height(ui_TestMotorMeterPointorPanel, 12);
    lv_obj_set_x(ui_TestMotorMeterPointorPanel, 0);
    lv_obj_set_y(ui_TestMotorMeterPointorPanel, -43);
    lv_obj_set_align(ui_TestMotorMeterPointorPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TestMotorMeterPointorPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_TestMotorMeterPointorPanel, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TestMotorMeterPointorPanel, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TestMotorMeterPointorPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TestMotorMeterPointorPanel, lv_color_hex(0x565656), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TestMotorMeterPointorPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TestMotorConfigContainer = lv_obj_create(ui_TestMotorContainer);
    lv_obj_remove_style_all(ui_TestMotorConfigContainer);
    lv_obj_set_width(ui_TestMotorConfigContainer, 120);
    lv_obj_set_height(ui_TestMotorConfigContainer, 100);
    lv_obj_set_x(ui_TestMotorConfigContainer, 106);
    lv_obj_set_y(ui_TestMotorConfigContainer, 1);
    lv_obj_clear_flag(ui_TestMotorConfigContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TestMotorConfigCheckbox1 = lv_checkbox_create(ui_TestMotorConfigContainer);
    lv_obj_set_height(ui_TestMotorConfigCheckbox1, 20);
    lv_obj_set_width(ui_TestMotorConfigCheckbox1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_TestMotorConfigCheckbox1, 2);
    lv_obj_set_y(ui_TestMotorConfigCheckbox1, 3);
    lv_obj_add_flag(ui_TestMotorConfigCheckbox1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_TestMotorConfigCheckbox2 = lv_checkbox_create(ui_TestMotorConfigContainer);
    lv_obj_set_height(ui_TestMotorConfigCheckbox2, 20);
    lv_obj_set_width(ui_TestMotorConfigCheckbox2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_TestMotorConfigCheckbox2, 2);
    lv_obj_set_y(ui_TestMotorConfigCheckbox2, 28);
    lv_obj_add_flag(ui_TestMotorConfigCheckbox2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_TestMotorConfigCheckbox3 = lv_checkbox_create(ui_TestMotorConfigContainer);
    lv_obj_set_height(ui_TestMotorConfigCheckbox3, 20);
    lv_obj_set_width(ui_TestMotorConfigCheckbox3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_TestMotorConfigCheckbox3, 2);
    lv_obj_set_y(ui_TestMotorConfigCheckbox3, 53);
    lv_obj_add_flag(ui_TestMotorConfigCheckbox3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_TestMotorConfigCheckbox4 = lv_checkbox_create(ui_TestMotorConfigContainer);
    lv_obj_set_height(ui_TestMotorConfigCheckbox4, 20);
    lv_obj_set_width(ui_TestMotorConfigCheckbox4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_TestMotorConfigCheckbox4, 2);
    lv_obj_set_y(ui_TestMotorConfigCheckbox4, 78);
    lv_obj_add_flag(ui_TestMotorConfigCheckbox4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_TestMotorDebugPanel = lv_obj_create(ui_TestMotorContainer);
    lv_obj_set_width(ui_TestMotorDebugPanel, 318);
    lv_obj_set_height(ui_TestMotorDebugPanel, 96);
    lv_obj_set_x(ui_TestMotorDebugPanel, 1);
    lv_obj_set_y(ui_TestMotorDebugPanel, -1);
    lv_obj_set_align(ui_TestMotorDebugPanel, LV_ALIGN_BOTTOM_LEFT);

    ui_TestMotorDebugLabel = lv_label_create(ui_TestMotorDebugPanel);
    lv_obj_set_width(ui_TestMotorDebugLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TestMotorDebugLabel, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_TestMotorDebugLabel,
                      "Communication : true\nGyro : 70 , -45\nBallDeg : 170 , -60\nYellowGoalDeg : 10 , -30\nBlueGoalDeg : -140 , -100\nPosition : (10,60) , (-10,-100)\nPosition : (10,-100)");

    lv_obj_add_event_cb(ui_TestDropdown, ui_event_TestDropdown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TestBackButton, ui_event_TestBackButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TestKickerLeverRearButton, ui_event_TestKickerLeverRearButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TestKickerLeverFrontButton, ui_event_TestKickerLeverFrontButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TestDribblerLeverRearButton, ui_event_TestDribblerLeverRearButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TestDribblerLeverFrontButton, ui_event_TestDribblerLeverFrontButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TestDribblerLeverRunButton, ui_event_TestDribblerLeverRunButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TestDribblerLeverIdleButton, ui_event_TestDribblerLeverIdleButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TestMotorLeverRunButton, ui_event_TestMotorLeverRunButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TestMotorLeverIdleButton, ui_event_TestMotorLeverIdleButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TestMotorMeterButton, ui_event_TestMotorMeterButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Test, ui_event_Test, LV_EVENT_ALL, NULL);

}

void ui_Test_screen_destroy(void)
{
    if(ui_Test) lv_obj_del(ui_Test);

    // NULL screen variables
    ui_Test = NULL;
    ui_TestTopContainer = NULL;
    ui_TestDropdown = NULL;
    ui_TestBackButton = NULL;
    ui_TestBackLabel = NULL;
    ui_TestMidContainer = NULL;
    ui_TestKickerContainer = NULL;
    ui_TestKickerLeverContainer = NULL;
    ui_TestKickerLeverRearButton = NULL;
    ui_TestKickerLeverRearLabel = NULL;
    ui_TestKickerLeverFrontButton = NULL;
    ui_TestKickerLeverFrontLabel = NULL;
    ui_TestKickerKickButton = NULL;
    ui_TestKickerKickLabel = NULL;
    ui_TestKickerDebugPanel = NULL;
    ui_TestKickerDebugLabel = NULL;
    ui_TestDribblerContainer = NULL;
    ui_TestDribblerLeverContainer1 = NULL;
    ui_TestDribblerLeverRearButton = NULL;
    ui_TestDribblerLeverRearLabel = NULL;
    ui_TestDribblerLeverFrontButton = NULL;
    ui_TestDribblerLeverFrontLabel = NULL;
    ui_TestDribblerLeverContainer2 = NULL;
    ui_TestDribblerLeverRunButton = NULL;
    ui_TestDribblerLeverRunLabel = NULL;
    ui_TestDribblerLeverIdleButton = NULL;
    ui_TestDribblerLeverIdleLabel = NULL;
    ui_TestDribblerDebugPanel = NULL;
    ui_TestDribblerDebugLabel = NULL;
    ui_TestMotorContainer = NULL;
    ui_TestMotorLeverContainer = NULL;
    ui_TestMotorLeverRunButton = NULL;
    ui_TestMotorLeverRunLabel = NULL;
    ui_TestMotorLeverIdleButton = NULL;
    ui_TestMotorLeverIdleLabel = NULL;
    ui_TestMotorMeterContainer = NULL;
    ui_TestMotorMeterPanel = NULL;
    ui_TestMotorMeterButton = NULL;
    ui_TestMotorMeterPointorPanel = NULL;
    ui_TestMotorConfigContainer = NULL;
    ui_TestMotorConfigCheckbox1 = NULL;
    ui_TestMotorConfigCheckbox2 = NULL;
    ui_TestMotorConfigCheckbox3 = NULL;
    ui_TestMotorConfigCheckbox4 = NULL;
    ui_TestMotorDebugPanel = NULL;
    ui_TestMotorDebugLabel = NULL;

}
