// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: test

#include "ui.h"

lv_obj_t * uic_Label5;
lv_obj_t * uic_BackButton1;
lv_obj_t * uic_DropDown1;
lv_obj_t * uic_TestAppScreen;
lv_obj_t * ui_TestAppScreen = NULL;
lv_obj_t * ui_DropDown1 = NULL;
lv_obj_t * ui_BackButton1 = NULL;
lv_obj_t * ui_Label5 = NULL;
// event funtions
void ui_event_DropDown1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        TestAppDropDownFunc(e);
    }
}

void ui_event_BackButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_HomeScreen, LV_SCR_LOAD_ANIM_FADE_ON, 10, 0, &ui_HomeScreen_screen_init);
    }
}

// build funtions

void ui_TestAppScreen_screen_init(void)
{
    ui_TestAppScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_TestAppScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DropDown1 = lv_dropdown_create(ui_TestAppScreen);
    lv_dropdown_set_dir(ui_DropDown1, LV_DIR_TOP);
    lv_dropdown_set_options(ui_DropDown1, "Kicker\nDribbler\nBno\nCam");
    lv_obj_set_width(ui_DropDown1, 248);
    lv_obj_set_height(ui_DropDown1, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_x(ui_DropDown1, 3);
    lv_obj_set_y(ui_DropDown1, 3);
    lv_obj_add_flag(ui_DropDown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_BackButton1 = lv_btn_create(ui_TestAppScreen);
    lv_obj_set_width(ui_BackButton1, 60);
    lv_obj_set_height(ui_BackButton1, 35);
    lv_obj_set_x(ui_BackButton1, 257);
    lv_obj_set_y(ui_BackButton1, 3);
    lv_obj_add_flag(ui_BackButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BackButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BackButton1, lv_color_hex(0xFF4F4F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BackButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_BackButton1);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "BACK");

    lv_obj_add_event_cb(ui_DropDown1, ui_event_DropDown1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BackButton1, ui_event_BackButton1, LV_EVENT_ALL, NULL);
    uic_TestAppScreen = ui_TestAppScreen;
    uic_DropDown1 = ui_DropDown1;
    uic_BackButton1 = ui_BackButton1;
    uic_Label5 = ui_Label5;

}

void ui_TestAppScreen_screen_destroy(void)
{
    if(ui_TestAppScreen) lv_obj_del(ui_TestAppScreen);

    // NULL screen variables
    uic_TestAppScreen = NULL;
    ui_TestAppScreen = NULL;
    uic_DropDown1 = NULL;
    ui_DropDown1 = NULL;
    uic_BackButton1 = NULL;
    ui_BackButton1 = NULL;
    uic_Label5 = NULL;
    ui_Label5 = NULL;

}
