// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_TEST_H
#define UI_TEST_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Test
extern void ui_Test_screen_init(void);
extern void ui_Test_screen_destroy(void);
extern lv_obj_t * ui_Test;
extern lv_obj_t * ui_TestTopContainer;
extern void ui_event_TestDropdown(lv_event_t * e);
extern lv_obj_t * ui_TestDropdown;
extern void ui_event_TestBackButton(lv_event_t * e);
extern lv_obj_t * ui_TestBackButton;
extern lv_obj_t * ui_TestBackLabel;
extern lv_obj_t * ui_TestMidContainer;
extern lv_obj_t * ui_TestKickerContainer;
extern lv_obj_t * ui_TestKickerLeverContainer;
extern void ui_event_TestKickerLeverRearButton(lv_event_t * e);
extern lv_obj_t * ui_TestKickerLeverRearButton;
extern lv_obj_t * ui_TestKickerLeverRearLabel;
extern void ui_event_TestKickerLeverFrontButton(lv_event_t * e);
extern lv_obj_t * ui_TestKickerLeverFrontButton;
extern lv_obj_t * ui_TestKickerLeverFrontLabel;
extern lv_obj_t * ui_TestKickerKickButton;
extern lv_obj_t * ui_TestKickerKickLabel;
extern lv_obj_t * ui_TestKickerDebugPanel;
extern lv_obj_t * ui_TestKickerDebugLabel;
extern lv_obj_t * ui_TestDribblerContainer;
extern lv_obj_t * ui_TestDribblerLeverContainer1;
extern void ui_event_TestDribblerLeverRearButton(lv_event_t * e);
extern lv_obj_t * ui_TestDribblerLeverRearButton;
extern lv_obj_t * ui_TestDribblerLeverRearLabel;
extern void ui_event_TestDribblerLeverFrontButton(lv_event_t * e);
extern lv_obj_t * ui_TestDribblerLeverFrontButton;
extern lv_obj_t * ui_TestDribblerLeverFrontLabel;
extern lv_obj_t * ui_TestDribblerLeverContainer2;
extern void ui_event_TestDribblerLeverRunButton(lv_event_t * e);
extern lv_obj_t * ui_TestDribblerLeverRunButton;
extern lv_obj_t * ui_TestDribblerLeverRunLabel;
extern void ui_event_TestDribblerLeverIdleButton(lv_event_t * e);
extern lv_obj_t * ui_TestDribblerLeverIdleButton;
extern lv_obj_t * ui_TestDribblerLeverIdleLabel;
extern lv_obj_t * ui_TestDribblerDebugPanel;
extern lv_obj_t * ui_TestDribblerDebugLabel;
extern lv_obj_t * ui_TestMotorContainer;
extern lv_obj_t * ui_TestMotorLeverContainer;
extern void ui_event_TestMotorLeverRunButton(lv_event_t * e);
extern lv_obj_t * ui_TestMotorLeverRunButton;
extern lv_obj_t * ui_TestMotorLeverRunLabel;
extern void ui_event_TestMotorLeverIdleButton(lv_event_t * e);
extern lv_obj_t * ui_TestMotorLeverIdleButton;
extern lv_obj_t * ui_TestMotorLeverIdleLabel;
extern lv_obj_t * ui_TestMotorMeterContainer;
extern lv_obj_t * ui_TestMotorMeterPanel;
extern void ui_event_TestMotorMeterButton(lv_event_t * e);
extern lv_obj_t * ui_TestMotorMeterButton;
extern lv_obj_t * ui_TestMotorMeterPointorPanel;
extern lv_obj_t * ui_TestMotorConfigContainer;
extern lv_obj_t * ui_TestMotorConfigCheckbox1;
extern lv_obj_t * ui_TestMotorConfigCheckbox2;
extern lv_obj_t * ui_TestMotorConfigCheckbox3;
extern lv_obj_t * ui_TestMotorConfigCheckbox4;
extern lv_obj_t * ui_TestMotorDebugPanel;
extern lv_obj_t * ui_TestMotorDebugLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

