// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: test

#ifndef UI_TESTAPPSCREEN_H
#define UI_TESTAPPSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_TestAppScreen
extern void ui_TestAppScreen_screen_init(void);
extern void ui_TestAppScreen_screen_destroy(void);
extern lv_obj_t * ui_TestAppScreen;
extern lv_obj_t * ui_DropDown1;
extern void ui_event_BackButton1(lv_event_t * e);
extern lv_obj_t * ui_BackButton1;
extern lv_obj_t * ui_Label5;
// CUSTOM VARIABLES
extern lv_obj_t * uic_TestAppScreen;
extern lv_obj_t * uic_DropDown1;
extern lv_obj_t * uic_BackButton1;
extern lv_obj_t * uic_Label5;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

