// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: test

#ifndef UI_TESTAPPSCREEN_H
#define UI_TESTAPPSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_TestAppScreen
extern void ui_TestAppScreen_screen_init(void);
extern void ui_TestAppScreen_screen_destroy(void);
extern lv_obj_t * ui_TestAppScreen;
extern void ui_event_DropDown1(lv_event_t * e);
extern lv_obj_t * ui_DropDown1;
extern void ui_event_BackButton1(lv_event_t * e);
extern lv_obj_t * ui_BackButton1;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Kicker;
extern void ui_event_KickerButton(lv_event_t * e);
extern lv_obj_t * ui_KickerButton;
extern lv_obj_t * ui_KickerLabel;
extern lv_obj_t * ui_FreePanel6;
extern lv_obj_t * ui_Direction;
extern void ui_event_FrontButton(lv_event_t * e);
extern lv_obj_t * ui_FrontButton;
extern lv_obj_t * ui_Label18;
extern void ui_event_BackButton(lv_event_t * e);
extern lv_obj_t * ui_BackButton;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_PIDMove;
extern lv_obj_t * ui_FreePanel7;
extern lv_obj_t * ui_Run3;
extern void ui_event_RunButton3(lv_event_t * e);
extern lv_obj_t * ui_RunButton3;
extern lv_obj_t * ui_Label13;
extern void ui_event_IdleButton3(lv_event_t * e);
extern lv_obj_t * ui_IdleButton3;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_BallMove;
extern lv_obj_t * ui_FreePanel8;
extern lv_obj_t * ui_Run2;
extern void ui_event_RunButton2(lv_event_t * e);
extern lv_obj_t * ui_RunButton2;
extern lv_obj_t * ui_Label15;
extern void ui_event_IdleButton2(lv_event_t * e);
extern lv_obj_t * ui_IdleButton2;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_LineMove;
extern lv_obj_t * ui_FreePanel9;
extern lv_obj_t * ui_Run4;
extern void ui_event_RunButton4(lv_event_t * e);
extern lv_obj_t * ui_RunButton4;
extern lv_obj_t * ui_Label20;
extern void ui_event_IdleButton4(lv_event_t * e);
extern lv_obj_t * ui_IdleButton4;
extern lv_obj_t * ui_Label17;
// CUSTOM VARIABLES
extern lv_obj_t * uic_TestAppScreen;
extern lv_obj_t * uic_DropDown1;
extern lv_obj_t * uic_BackButton1;
extern lv_obj_t * uic_Label5;
extern lv_obj_t * uic_Kicker;
extern lv_obj_t * uic_KickerButton;
extern lv_obj_t * uic_KickerLabel;
extern lv_obj_t * uic_FreePanel6;
extern lv_obj_t * uic_Direction;
extern lv_obj_t * uic_FrontButton;
extern lv_obj_t * uic_Label18;
extern lv_obj_t * uic_BackButton;
extern lv_obj_t * uic_Label14;
extern lv_obj_t * uic_PIDMove;
extern lv_obj_t * uic_FreePanel7;
extern lv_obj_t * uic_Run3;
extern lv_obj_t * uic_RunButton3;
extern lv_obj_t * uic_Label13;
extern lv_obj_t * uic_IdleButton3;
extern lv_obj_t * uic_Label10;
extern lv_obj_t * uic_BallMove;
extern lv_obj_t * uic_FreePanel8;
extern lv_obj_t * uic_Run2;
extern lv_obj_t * uic_RunButton2;
extern lv_obj_t * uic_Label15;
extern lv_obj_t * uic_IdleButton2;
extern lv_obj_t * uic_Label16;
extern lv_obj_t * uic_LineMove;
extern lv_obj_t * uic_FreePanel9;
extern lv_obj_t * uic_Run4;
extern lv_obj_t * uic_RunButton4;
extern lv_obj_t * uic_Label20;
extern lv_obj_t * uic_IdleButton4;
extern lv_obj_t * uic_Label17;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

